"""Closed deterministic source-fact acquisition boundary."""

from asklegal_domain import SourceOutageImpact

from .admission import (
    ContentAdmissionInput,
    ResponseAdmissionPolicy,
    admit_response,
    classify_content,
)
from .hk_cases_official import (
    HK_CASE_SOURCE_ACCESS_FORBIDDEN_EFFECTS,
    HK_CASE_SOURCE_IDS,
    HongKongCasesAccessBoundary,
    HongKongCasesSourceProfile,
    HongKongCasesSourceRegister,
    load_hk_cases_source_register,
)
from .hkel_gazette import (
    CAPABILITY_CLAIM,
    GazetteEntry,
    GazettePage,
    GazetteRegisterError,
    GazetteRegisterFailureCode,
    GazetteRequestTiming,
    HkelGazetteRegisterClient,
)
from .model import (
    AcquisitionArtifact,
    AcquisitionConsequence,
    AcquisitionOutcome,
    AuthenticationClass,
    ConnectorRequest,
    CoverageAccounting,
    CoverageAccountingResult,
    EndpointContract,
    HttpMethod,
    ObservationDisposition,
    RegisteredSource,
    RetryProfile,
    ScraperResult,
    ScraperResultCode,
    SourcePolicyState,
    SourceRegistry,
    SyntheticPage,
    SyntheticResponse,
    WatcherResult,
    WatcherResultCode,
)
from .official import (
    HK_LEGISLATION_SOURCE_IDS,
    EndpointAccessMode,
    HongKongLegislationSourceRegister,
    LegalClearanceAttestation,
    OfficialAccessAuthorization,
    OfficialEndpointContract,
    OfficialSourceProfile,
    OfficialSourceState,
    PublisherRightsEvidence,
    PublisherRightsState,
    SignalUse,
    load_hk_legislation_source_register,
)
from .official_binding import BoundOfficialEndpoint, bind_official_endpoint_locator
from .official_http import (
    OfficialFetchCode,
    OfficialFetchRequest,
    OfficialFetchResult,
    OfficialHttpConnector,
    OfficialHttpTransport,
    OfficialObservationGate,
    OfficialTransportFailure,
    OfficialTransportResponse,
    PolicyBoundOfficialHttpTransport,
    ProxiedOfficialHttpTransport,
    PublisherCall,
    StdlibOfficialHttpTransport,
)
from .official_inventory import (
    OfficialInventoryCode,
    OfficialInventoryConnector,
    OfficialInventoryRequest,
    OfficialInventoryResult,
)
from .official_monitoring import (
    HK_LEGISLATION_MONITORING_ASSIGNMENTS,
    OfficialCoverageCycle,
    OfficialMonitoringAssignment,
    OfficialMonitoringTier,
    OfficialObservationProfile,
    due_official_source_ids,
    due_official_source_profiles,
    official_observation_profile,
)
from .official_planning import (
    OfficialEndpointBuildAssessment,
    OfficialSourceBuildAssessment,
    OfficialSourceBuildReport,
    assess_official_source_build,
)
from .official_rendered import (
    OfficialRenderedFetchRequest,
    OfficialRenderedSessionConnector,
    OfficialRenderedSessionTransport,
)
from .synthetic import SyntheticConnector

PACKAGE_ROLE: str = "source-connectors"

__all__ = [
    "CAPABILITY_CLAIM",
    "HK_CASE_SOURCE_ACCESS_FORBIDDEN_EFFECTS",
    "HK_CASE_SOURCE_IDS",
    "HK_LEGISLATION_MONITORING_ASSIGNMENTS",
    "HK_LEGISLATION_SOURCE_IDS",
    "PACKAGE_ROLE",
    "AcquisitionArtifact",
    "AcquisitionConsequence",
    "AcquisitionOutcome",
    "AuthenticationClass",
    "BoundOfficialEndpoint",
    "ConnectorRequest",
    "ContentAdmissionInput",
    "CoverageAccounting",
    "CoverageAccountingResult",
    "EndpointAccessMode",
    "EndpointContract",
    "GazetteEntry",
    "GazettePage",
    "GazetteRegisterError",
    "GazetteRegisterFailureCode",
    "GazetteRequestTiming",
    "HkelGazetteRegisterClient",
    "HongKongCasesAccessBoundary",
    "HongKongCasesSourceProfile",
    "HongKongCasesSourceRegister",
    "HongKongLegislationSourceRegister",
    "HttpMethod",
    "LegalClearanceAttestation",
    "ObservationDisposition",
    "OfficialAccessAuthorization",
    "OfficialCoverageCycle",
    "OfficialEndpointBuildAssessment",
    "OfficialEndpointContract",
    "OfficialFetchCode",
    "OfficialFetchRequest",
    "OfficialFetchResult",
    "OfficialHttpConnector",
    "OfficialHttpTransport",
    "OfficialInventoryCode",
    "OfficialInventoryConnector",
    "OfficialInventoryRequest",
    "OfficialInventoryResult",
    "OfficialMonitoringAssignment",
    "OfficialMonitoringTier",
    "OfficialObservationGate",
    "OfficialObservationProfile",
    "OfficialRenderedFetchRequest",
    "OfficialRenderedSessionConnector",
    "OfficialRenderedSessionTransport",
    "OfficialSourceBuildAssessment",
    "OfficialSourceBuildReport",
    "OfficialSourceProfile",
    "OfficialSourceState",
    "OfficialTransportFailure",
    "OfficialTransportResponse",
    "PolicyBoundOfficialHttpTransport",
    "ProxiedOfficialHttpTransport",
    "PublisherCall",
    "PublisherRightsEvidence",
    "PublisherRightsState",
    "RegisteredSource",
    "ResponseAdmissionPolicy",
    "RetryProfile",
    "ScraperResult",
    "ScraperResultCode",
    "SignalUse",
    "SourceOutageImpact",
    "SourcePolicyState",
    "SourceRegistry",
    "StdlibOfficialHttpTransport",
    "SyntheticConnector",
    "SyntheticPage",
    "SyntheticResponse",
    "WatcherResult",
    "WatcherResultCode",
    "admit_response",
    "assess_official_source_build",
    "bind_official_endpoint_locator",
    "classify_content",
    "due_official_source_ids",
    "due_official_source_profiles",
    "load_hk_cases_source_register",
    "load_hk_legislation_source_register",
    "official_observation_profile",
]
