"""Framework-free application boundary contracts and local adapters."""

from asklegal_application_runtime.config import (
    ApplicationConfiguration,
    ConfigurationError,
    ConfigurationErrorCode,
    LocalConfigurationSource,
    RuntimeLimits,
    build_local_configuration,
)
from asklegal_application_runtime.credentials import (
    CredentialError,
    CredentialErrorCode,
    CredentialMaterial,
    SystemdCredentialDirectory,
)
from asklegal_application_runtime.identity import (
    AuthorizationError,
    AuthorizationErrorCode,
    LocalIdentityVerifier,
    Principal,
    TokenType,
    authorize,
    default_local_identity,
)
from asklegal_application_runtime.local import (
    CommandOutcome,
    DisabledEffectPort,
    LocalAdapterError,
    LocalAdapterErrorCode,
    LocalCommandRegister,
    LocalPaginationStore,
    LocalReviewProjectionStore,
    PageCursor,
    ProposalProjection,
)
from asklegal_application_runtime.probes import (
    V1_INTERNAL_CA_BUNDLE,
    V1_LOGICAL_DESTINATIONS,
    CallableProbe,
    TcpReachabilityProbe,
    TlsReachabilityProbe,
    destination_for,
)
from asklegal_application_runtime.readiness import (
    DependencyCode,
    ProbeResult,
    ProbeStatus,
    ReadinessError,
    ReadinessErrorCode,
    ReadinessProbe,
    ReadinessProbeFailure,
    ReadinessReport,
    V1ReadinessGate,
    required_v1_dependencies,
)
from asklegal_application_runtime.service import (
    ServeCallable,
    ServiceExitCode,
    format_readiness,
    run_v1_service,
    unready_dependencies,
)
from asklegal_application_runtime.worker import (
    LocalTaskHub,
    WorkerResultCode,
    WorkerRuntime,
    WorkLease,
)

PACKAGE_ROLE: str = "application-runtime"

__all__ = [
    "PACKAGE_ROLE",
    "V1_INTERNAL_CA_BUNDLE",
    "V1_LOGICAL_DESTINATIONS",
    "ApplicationConfiguration",
    "AuthorizationError",
    "AuthorizationErrorCode",
    "CallableProbe",
    "CommandOutcome",
    "ConfigurationError",
    "ConfigurationErrorCode",
    "CredentialError",
    "CredentialErrorCode",
    "CredentialMaterial",
    "DependencyCode",
    "DisabledEffectPort",
    "LocalAdapterError",
    "LocalAdapterErrorCode",
    "LocalCommandRegister",
    "LocalConfigurationSource",
    "LocalIdentityVerifier",
    "LocalPaginationStore",
    "LocalReviewProjectionStore",
    "LocalTaskHub",
    "PageCursor",
    "Principal",
    "ProbeResult",
    "ProbeStatus",
    "ProposalProjection",
    "ReadinessError",
    "ReadinessErrorCode",
    "ReadinessProbe",
    "ReadinessProbeFailure",
    "ReadinessReport",
    "RuntimeLimits",
    "ServeCallable",
    "ServiceExitCode",
    "SystemdCredentialDirectory",
    "TcpReachabilityProbe",
    "TlsReachabilityProbe",
    "TokenType",
    "V1ReadinessGate",
    "WorkLease",
    "WorkerResultCode",
    "WorkerRuntime",
    "authorize",
    "build_local_configuration",
    "default_local_identity",
    "destination_for",
    "format_readiness",
    "required_v1_dependencies",
    "run_v1_service",
    "unready_dependencies",
]
