#!/usr/bin/env bash
# Generated by tools/v1_poc_render_units.py. Do not edit by hand.
#
# Seal every V1 credential to this host, encrypted at rest.
#
# Reads one plaintext file per credential from a staging directory you supply,
# and writes the sealed form under /etc/asklegal/credentials. The sealed files are
# useless on any other machine. Delete the staging directory afterwards: this
# script will not do it for you, because it does not own those files.
#
#   sudo ./70-credentials.sh /path/to/plaintext-staging
set -euo pipefail

staging="${1:-}"
if [ -z "$staging" ] || [ ! -d "$staging" ]; then
  printf "usage: %s <plaintext-staging-directory>\n" "$0" >&2
  exit 1
fi
if [ "$(id -u)" -ne 0 ]; then
  printf "this step must run as root\n" >&2
  exit 1
fi

install -d -o root -g root -m 0700 '/etc/asklegal/credentials'

# host+tpm2 binds the key to this machine's TPM. If the TPM is unavailable the
# command fails rather than silently falling back to a host-only key.
seal() {
  local name="$1"
  if [ ! -f "$staging/$name" ]; then
    printf "missing plaintext credential: %s\n" "$name" >&2
    exit 1
  fi
  systemd-creds encrypt --with-key=host+tpm2 --name="$name" \
    "$staging/$name" '/etc/asklegal/credentials'/"$name".cred
  chmod 0400 '/etc/asklegal/credentials'/"$name".cred
  printf "sealed %s\n" "$name"
}

seal 'embedding-provider'
seal 'model-egress-proxy'
seal 'pinecone-poc'
seal 'promotion-egress-proxy'
seal 'review-api'
seal 'review-client'
seal 'source-egress-proxy'
seal 'sql-acquisition'
seal 'sql-bootstrap-password'
seal 'sql-control'
seal 'sql-processing'
seal 'sql-promotion'
seal 'sql-review'
seal 'vault-primary-acquisition'
seal 'vault-primary-control'
seal 'vault-primary-processing'
seal 'vault-primary-promotion'
seal 'vault-primary-review'
seal 'vault-primary-root-access'
seal 'vault-primary-root-secret'
seal 'vault-recovery-acquisition'
seal 'vault-recovery-promotion'
seal 'vault-recovery-root-access'
seal 'vault-recovery-root-secret'

printf "\n%s credentials sealed under %s\n" 24 '/etc/asklegal/credentials'
printf "Now delete your plaintext staging directory.\n"
