#!/usr/bin/env bash
# Generated by tools/v1_poc_render_units.py. Do not edit by hand.
#
# Install the V1 POC units, launchers, and service configuration.
#
# This installs and does not enable. Nothing starts at boot until you run the
# enable command this script prints at the end, so you can read every file
# first. Run 70-credentials.sh before enabling, or every unit that needs a
# credential will fail to start.
set -euo pipefail

if [ "$(id -u)" -ne 0 ]; then
  printf "this step must run as root\n" >&2
  exit 1
fi
here="$(cd "$(dirname "$0")" && pwd)"
repository="$(cd "$here/../../.." && pwd)"

install -d -o root -g root -m 0755 '/etc/asklegal/launch' '/etc/asklegal/config'
install -d -o root -g root -m 0755 /etc/asklegal/trust
install -d -o root -g root -m 0755 /usr/local/libexec
install -d -o root -g root -m 0755 /opt/asklegal/management-register

# The internal authority has to be in the container trust store as well as on
# its own, because the SQL driver validates against the system bundle.
cat /etc/ssl/certs/ca-certificates.crt /etc/asklegal/tls/internal-ca.crt \
  > /etc/asklegal/trust/ca-certificates.crt
chmod 0644 /etc/asklegal/trust/ca-certificates.crt
for vault in vault-primary vault-recovery; do
  cp /etc/asklegal/tls/internal-ca.crt "/etc/asklegal/trust/$vault-ca.pem"
  chmod 0644 "/etc/asklegal/trust/$vault-ca.pem"
done

install -o root -g root -m 0644 \
  "$repository"/infrastructure/poc/config/* '/etc/asklegal/config'/
install -o root -g root -m 0755 "$here"/launch/*.sh '/etc/asklegal/launch'/
install -o root -g root -m 0755 "$repository"/infrastructure/poc/libexec/asklegal-register-migrate /usr/local/libexec/asklegal-register-migrate
install -o root -g root -m 0755 "$repository"/infrastructure/poc/libexec/asklegal-vault-bootstrap /usr/local/libexec/asklegal-vault-bootstrap
install -o root -g root -m 0755 "$repository"/infrastructure/poc/libexec/asklegal-vault-application-rotation-network /usr/local/libexec/asklegal-vault-application-rotation-network
migration_stage="$(mktemp -d /opt/asklegal/management-register/.migrations.XXXXXXXX)"
trap 'rm -rf -- "$migration_stage"' EXIT
cp -a "$repository"/packages/management-register-adapter/migrations/. "$migration_stage"/
find "$migration_stage" -type d -exec chmod 0755 {} +
find "$migration_stage" -type f -exec chmod 0644 {} +
chown -R root:root "$migration_stage"
rm -rf -- /opt/asklegal/management-register/migrations
mv -- "$migration_stage" /opt/asklegal/management-register/migrations
trap - EXIT
install -o root -g root -m 0644 "$here"/*.service "$here"/*.target "$here"/*.timer /etc/systemd/system/

systemctl daemon-reload
printf "\ninstalled %s units, not enabled\n" 28

printf "\nWhen you are ready, and only after 70-credentials.sh:\n"
printf "  sudo systemctl enable --now asklegal.target\n"
