#!/usr/bin/env bash
# Generated by tools/v1_poc_render_units.py. Do not edit by hand.
#
# Install the V1 POC units, launchers, and service configuration.
#
# This installs and does not enable. Nothing starts at boot until you run the
# enable command this script prints at the end, so you can read every file
# first. Run 70-credentials.sh before enabling, or every unit that needs a
# credential will fail to start.
set -euo pipefail

if [ "$(id -u)" -ne 0 ]; then
  printf "this step must run as root\n" >&2
  exit 1
fi
here="$(cd "$(dirname "$0")" && pwd)"
repository="$(cd "$here/../../.." && pwd)"

install -d -o root -g root -m 0755 '/etc/asklegal/launch' '/etc/asklegal/config'
install -d -o root -g root -m 0755 /etc/asklegal/trust

# The internal authority has to be in the container trust store as well as on
# its own, because the SQL driver validates against the system bundle.
cat /etc/ssl/certs/ca-certificates.crt /etc/asklegal/tls/internal-ca.crt \
  > /etc/asklegal/trust/ca-certificates.crt
chmod 0644 /etc/asklegal/trust/ca-certificates.crt
for vault in vault-primary vault-recovery; do
  cp /etc/asklegal/tls/internal-ca.crt "/etc/asklegal/trust/$vault-ca.pem"
  chmod 0644 "/etc/asklegal/trust/$vault-ca.pem"
done

install -o root -g root -m 0644 \
  "$repository"/infrastructure/poc/config/* '/etc/asklegal/config'/
install -o root -g root -m 0755 "$here"/launch/*.sh '/etc/asklegal/launch'/
install -o root -g root -m 0644 "$here"/*.service "$here"/*.target /etc/systemd/system/

systemctl daemon-reload
printf "\ninstalled %s units, not enabled\n" 14

printf "\nWhen you are ready, and only after 70-credentials.sh:\n"
printf "  sudo systemctl enable --now asklegal.target\n"
