GRANT EXECUTE ON OBJECT::promotion.read_serving_state_v1 TO asklegal_promotion_role;
GRANT EXECUTE ON OBJECT::promotion.activate_serving_state_v1 TO asklegal_promotion_role;
GRANT EXECUTE ON OBJECT::promotion.rollback_serving_state_v1 TO asklegal_promotion_role;
DENY EXECUTE ON OBJECT::promotion.read_serving_state_v1 TO asklegal_control_role;
DENY EXECUTE ON OBJECT::promotion.read_serving_state_v1 TO asklegal_review_role;
DENY EXECUTE ON OBJECT::promotion.read_serving_state_v1 TO asklegal_acquisition_role;
DENY EXECUTE ON OBJECT::promotion.read_serving_state_v1 TO asklegal_legal_processing_role;
DENY EXECUTE ON OBJECT::promotion.activate_serving_state_v1 TO asklegal_control_role;
DENY EXECUTE ON OBJECT::promotion.activate_serving_state_v1 TO asklegal_review_role;
DENY EXECUTE ON OBJECT::promotion.activate_serving_state_v1 TO asklegal_acquisition_role;
DENY EXECUTE ON OBJECT::promotion.activate_serving_state_v1 TO asklegal_legal_processing_role;
DENY EXECUTE ON OBJECT::promotion.rollback_serving_state_v1 TO asklegal_control_role;
DENY EXECUTE ON OBJECT::promotion.rollback_serving_state_v1 TO asklegal_review_role;
DENY EXECUTE ON OBJECT::promotion.rollback_serving_state_v1 TO asklegal_acquisition_role;
DENY EXECUTE ON OBJECT::promotion.rollback_serving_state_v1 TO asklegal_legal_processing_role;
DENY SELECT, INSERT, UPDATE, DELETE ON OBJECT::promotion.serving_state_v1_current TO asklegal_promotion_role;
DENY SELECT, INSERT, UPDATE, DELETE ON OBJECT::promotion.serving_state_v1_fact TO asklegal_promotion_role;
DENY SELECT, INSERT, UPDATE, DELETE ON OBJECT::promotion.serving_state_v1_current TO asklegal_control_role;
DENY SELECT, INSERT, UPDATE, DELETE ON OBJECT::promotion.serving_state_v1_fact TO asklegal_control_role;
DENY SELECT, INSERT, UPDATE, DELETE ON OBJECT::promotion.serving_state_v1_current TO asklegal_review_role;
DENY SELECT, INSERT, UPDATE, DELETE ON OBJECT::promotion.serving_state_v1_fact TO asklegal_review_role;
DENY SELECT, INSERT, UPDATE, DELETE ON OBJECT::promotion.serving_state_v1_current TO asklegal_acquisition_role;
DENY SELECT, INSERT, UPDATE, DELETE ON OBJECT::promotion.serving_state_v1_fact TO asklegal_acquisition_role;
DENY SELECT, INSERT, UPDATE, DELETE ON OBJECT::promotion.serving_state_v1_current TO asklegal_legal_processing_role;
DENY SELECT, INSERT, UPDATE, DELETE ON OBJECT::promotion.serving_state_v1_fact TO asklegal_legal_processing_role;
