#!/usr/bin/env bash
# Generated by tools/v1_poc_render_units.py. Do not edit by hand.
#
# Start acquisition-worker exactly as it was proved to run.
set -euo pipefail

container='asklegal-acquisition-worker'
runtime_uid=3000

# A stale container from a previous boot would keep the name and the old
# configuration, so the unit always starts from a clean one.
docker rm -f "$container" >/dev/null 2>&1 || true

# The application reads its own credentials as files owned by its runtime
# uid at mode 0400. $CREDENTIALS_DIRECTORY is root-owned, so copy rather
# than mount it, onto /run, which is a tmpfs.
credential_dir='/run/asklegal/credentials/acquisition-worker'
rm -rf "$credential_dir"
mkdir -p "$credential_dir"
install -o "$runtime_uid" -g "$runtime_uid" -m 0400 "$CREDENTIALS_DIRECTORY"/sql-acquisition "$credential_dir"/sql-acquisition
install -o "$runtime_uid" -g "$runtime_uid" -m 0400 "$CREDENTIALS_DIRECTORY"/vault-primary-acquisition "$credential_dir"/vault-primary-acquisition
install -o "$runtime_uid" -g "$runtime_uid" -m 0400 "$CREDENTIALS_DIRECTORY"/vault-recovery-acquisition "$credential_dir"/vault-recovery-acquisition
install -o "$runtime_uid" -g "$runtime_uid" -m 0400 "$CREDENTIALS_DIRECTORY"/source-egress-proxy "$credential_dir"/source-egress-proxy
chown "$runtime_uid":"$runtime_uid" "$credential_dir"
chmod 0500 "$credential_dir"

docker create \
  --name "$container" \
  --network 'asklegal-register' \
  --network-alias 'acquisition-worker' \
  --user "$runtime_uid":"$runtime_uid" \
  --cap-drop ALL \
  --security-opt no-new-privileges \
  -e 'CREDENTIALS_DIRECTORY=/run/credentials/asklegal-acquisition-worker.service' \
  -v "$credential_dir":'/run/credentials/asklegal-acquisition-worker.service':ro \
  -v '/etc/asklegal/trust/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro' \
  -v '/etc/asklegal/trust/vault-primary-ca.pem:/etc/asklegal/trust/vault-primary-ca.pem:ro' \
  -v '/etc/asklegal/trust/vault-recovery-ca.pem:/etc/asklegal/trust/vault-recovery-ca.pem:ro' \
  -v '/etc/asklegal/tls/internal-ca.crt:/etc/asklegal/tls/internal-ca.crt:ro' \
  'asklegal/acquisition-worker:v1' \
  'python' \
  '-m' \
  'asklegal_acquisition_worker.v1_service' >/dev/null

# Every network is attached before the process starts. Attaching after start
# is a race: the readiness gate can run before a dependency is reachable.
docker network connect --alias 'acquisition-worker' 'asklegal-scheduler-general' "$container"
docker network connect --alias 'acquisition-worker' 'asklegal-vault-primary' "$container"
docker network connect --alias 'acquisition-worker' 'asklegal-vault-recovery' "$container"
docker network connect --alias 'acquisition-worker' 'asklegal-telemetry' "$container"
docker network connect --alias 'acquisition-worker' 'asklegal-egress-source' "$container"

# `docker start --attach` keeps this script in the foreground so systemd can
# supervise it; ExecStop stops the container itself.
exec docker start --attach "$container"
