#!/usr/bin/env bash
# Generated by tools/v1_poc_render_units.py. Do not edit by hand.
#
# Start control-plane exactly as it was proved to run.
set -euo pipefail

container='asklegal-control-plane'
runtime_uid=3001

# A stale container from a previous boot would keep the name and the old
# configuration, so the unit always starts from a clean one.
docker rm -f "$container" >/dev/null 2>&1 || true

# The application reads its own credentials as files owned by its runtime
# uid at mode 0400. $CREDENTIALS_DIRECTORY is root-owned, so copy rather
# than mount it, onto /run, which is a tmpfs.
credential_dir='/run/asklegal/credentials/control-plane'
rm -rf "$credential_dir"
mkdir -p "$credential_dir"
install -o "$runtime_uid" -g "$runtime_uid" -m 0400 "$CREDENTIALS_DIRECTORY"/sql-control "$credential_dir"/sql-control
install -o "$runtime_uid" -g "$runtime_uid" -m 0400 "$CREDENTIALS_DIRECTORY"/review-client "$credential_dir"/review-client
install -o "$runtime_uid" -g "$runtime_uid" -m 0400 "$CREDENTIALS_DIRECTORY"/vault-primary-control "$credential_dir"/vault-primary-control
chown "$runtime_uid":"$runtime_uid" "$credential_dir"
chmod 0500 "$credential_dir"

docker create \
  --name "$container" \
  --network 'asklegal-register' \
  --network-alias 'control-plane' \
  --user "$runtime_uid":"$runtime_uid" \
  --cap-drop ALL \
  --security-opt no-new-privileges \
  -e 'CREDENTIALS_DIRECTORY=/run/credentials/asklegal-control-plane.service' \
  -v "$credential_dir":'/run/credentials/asklegal-control-plane.service':ro \
  -v '/etc/asklegal/trust/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro' \
  -v '/etc/asklegal/trust/vault-primary-ca.pem:/etc/asklegal/trust/vault-primary-ca.pem:ro' \
  -v '/etc/asklegal/trust/vault-recovery-ca.pem:/etc/asklegal/trust/vault-recovery-ca.pem:ro' \
  -v '/etc/asklegal/tls/internal-ca.crt:/etc/asklegal/tls/internal-ca.crt:ro' \
  'asklegal/control-plane:tls-c' \
  'python' \
  '-m' \
  'asklegal_control_plane.v1_service' >/dev/null

# Every network is attached before the process starts. Attaching after start
# is a race: the readiness gate can run before a dependency is reachable.
docker network connect --alias 'control-plane' 'asklegal-scheduler-general' "$container"
docker network connect --alias 'control-plane' 'asklegal-review' "$container"
docker network connect --alias 'control-plane' 'asklegal-telemetry' "$container"
docker network connect --alias 'control-plane' 'asklegal-vault-primary' "$container"

# `docker start --attach` keeps this script in the foreground so systemd can
# supervise it; ExecStop stops the container itself.
exec docker start --attach "$container"
