#!/usr/bin/env bash
# Generated by tools/v1_poc_render_units.py. Do not edit by hand.
#
# Start egress-model exactly as it was proved to run.
set -euo pipefail

container='asklegal-egress-model'
runtime_uid=3012

# A stale container from a previous boot would keep the name and the old
# configuration, so the unit always starts from a clean one.
docker rm -f "$container" >/dev/null 2>&1 || true

docker create \
  --name "$container" \
  --network 'asklegal-egress-model' \
  --network-alias 'egress-model' \
  --user "$runtime_uid":"$runtime_uid" \
  --cap-drop ALL \
  --security-opt no-new-privileges \
  --tmpfs '/var/run/squid':uid=$runtime_uid,gid=$runtime_uid,mode=0700 \
  --tmpfs '/var/log/squid':uid=$runtime_uid,gid=$runtime_uid,mode=0700 \
  --tmpfs '/var/spool/squid':uid=$runtime_uid,gid=$runtime_uid,mode=0700 \
  -v '/etc/asklegal/config/squid-model.conf:/etc/squid/squid.conf:ro' \
  'docker.io/ubuntu/squid@sha256:94f844158e12b52f51b4ae996515e37e8fb3e8d85e1c86caba1a297376e4ec4f' \
  'squid' \
  '-N' \
  '-f' \
  '/etc/squid/squid.conf' >/dev/null

# `docker start --attach` keeps this script in the foreground so systemd can
# supervise it; ExecStop stops the container itself.
exec docker start --attach "$container"
