#!/usr/bin/env bash
# Generated by tools/v1_poc_render_units.py. Do not edit by hand.
#
# Create any missing V1 network. Existing networks are left alone: this runs at
# every boot, and recreating a network would disconnect every running service.
set -euo pipefail

if ! docker network inspect 'asklegal-egress-model' >/dev/null 2>&1; then
  docker network create --driver bridge \
    --subnet '10.90.8.0/24' 'asklegal-egress-model' >/dev/null
  printf "created %s\n" 'asklegal-egress-model'
fi
if ! docker network inspect 'asklegal-egress-promotion' >/dev/null 2>&1; then
  docker network create --driver bridge \
    --subnet '10.90.9.0/24' 'asklegal-egress-promotion' >/dev/null
  printf "created %s\n" 'asklegal-egress-promotion'
fi
if ! docker network inspect 'asklegal-egress-source' >/dev/null 2>&1; then
  docker network create --driver bridge \
    --subnet '10.90.7.0/24' 'asklegal-egress-source' >/dev/null
  printf "created %s\n" 'asklegal-egress-source'
fi
if ! docker network inspect 'asklegal-register' >/dev/null 2>&1; then
  docker network create --driver bridge --internal \
    --subnet '10.90.0.0/24' 'asklegal-register' >/dev/null
  printf "created %s\n" 'asklegal-register'
fi
if ! docker network inspect 'asklegal-review' >/dev/null 2>&1; then
  docker network create --driver bridge --internal \
    --subnet '10.90.5.0/24' 'asklegal-review' >/dev/null
  printf "created %s\n" 'asklegal-review'
fi
if ! docker network inspect 'asklegal-scheduler-general' >/dev/null 2>&1; then
  docker network create --driver bridge --internal \
    --subnet '10.90.1.0/24' 'asklegal-scheduler-general' >/dev/null
  printf "created %s\n" 'asklegal-scheduler-general'
fi
if ! docker network inspect 'asklegal-scheduler-promotion' >/dev/null 2>&1; then
  docker network create --driver bridge --internal \
    --subnet '10.90.2.0/24' 'asklegal-scheduler-promotion' >/dev/null
  printf "created %s\n" 'asklegal-scheduler-promotion'
fi
if ! docker network inspect 'asklegal-telemetry' >/dev/null 2>&1; then
  docker network create --driver bridge --internal \
    --subnet '10.90.6.0/24' 'asklegal-telemetry' >/dev/null
  printf "created %s\n" 'asklegal-telemetry'
fi
if ! docker network inspect 'asklegal-vault-primary' >/dev/null 2>&1; then
  docker network create --driver bridge --internal \
    --subnet '10.90.3.0/24' 'asklegal-vault-primary' >/dev/null
  printf "created %s\n" 'asklegal-vault-primary'
fi
if ! docker network inspect 'asklegal-vault-recovery' >/dev/null 2>&1; then
  docker network create --driver bridge --internal \
    --subnet '10.90.4.0/24' 'asklegal-vault-recovery' >/dev/null
  printf "created %s\n" 'asklegal-vault-recovery'
fi
