#!/usr/bin/env bash
# Generated by tools/v1_poc_render_units.py. Do not edit by hand.
#
# Start otel-collector exactly as it was proved to run.
set -euo pipefail

container='asklegal-otel-collector'
runtime_uid=3004

# A stale container from a previous boot would keep the name and the old
# configuration, so the unit always starts from a clean one.
docker rm -f "$container" >/dev/null 2>&1 || true

docker create \
  --name "$container" \
  --network 'asklegal-telemetry' \
  --network-alias 'otel-collector' \
  --user "$runtime_uid":"$runtime_uid" \
  --cap-drop ALL \
  --security-opt no-new-privileges \
  --read-only \
  -v '/etc/asklegal/config/otel-collector.yaml:/etc/otelcol-contrib/config.yaml:ro' \
  'ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib@sha256:4f4276c07cee9055f2ab630a86330243f85e208c388ee697bea2a44dab896c3f' >/dev/null

# `docker start --attach` keeps this script in the foreground so systemd can
# supervise it; ExecStop stops the container itself.
exec docker start --attach "$container"
