#!/usr/bin/env bash
# Generated by tools/v1_poc_render_units.py. Do not edit by hand.
#
# Start promotion-worker exactly as it was proved to run.
set -euo pipefail

container='asklegal-promotion-worker'
runtime_uid=3006

# A stale container from a previous boot would keep the name and the old
# configuration, so the unit always starts from a clean one.
docker rm -f "$container" >/dev/null 2>&1 || true

# The application reads its own credentials as files owned by its runtime
# uid at mode 0400. $CREDENTIALS_DIRECTORY is root-owned, so copy rather
# than mount it, onto /run, which is a tmpfs.
credential_dir='/run/asklegal/credentials/promotion-worker'
rm -rf "$credential_dir"
mkdir -p "$credential_dir"
install -o "$runtime_uid" -g "$runtime_uid" -m 0400 "$CREDENTIALS_DIRECTORY"/sql-promotion "$credential_dir"/sql-promotion
install -o "$runtime_uid" -g "$runtime_uid" -m 0400 "$CREDENTIALS_DIRECTORY"/vault-primary-promotion "$credential_dir"/vault-primary-promotion
install -o "$runtime_uid" -g "$runtime_uid" -m 0400 "$CREDENTIALS_DIRECTORY"/vault-recovery-promotion "$credential_dir"/vault-recovery-promotion
install -o "$runtime_uid" -g "$runtime_uid" -m 0400 "$CREDENTIALS_DIRECTORY"/promotion-egress-proxy "$credential_dir"/promotion-egress-proxy
install -o "$runtime_uid" -g "$runtime_uid" -m 0400 "$CREDENTIALS_DIRECTORY"/pinecone-poc "$credential_dir"/pinecone-poc
install -o "$runtime_uid" -g "$runtime_uid" -m 0400 "$CREDENTIALS_DIRECTORY"/embedding-provider "$credential_dir"/embedding-provider
chown "$runtime_uid":"$runtime_uid" "$credential_dir"
chmod 0500 "$credential_dir"

docker create \
  --name "$container" \
  --network 'asklegal-register' \
  --network-alias 'promotion-worker' \
  --user "$runtime_uid":"$runtime_uid" \
  --cap-drop ALL \
  --security-opt no-new-privileges \
  -e 'PROMOTION_WRITE_AUTHORIZED=true' \
  -e 'CREDENTIALS_DIRECTORY=/run/credentials/asklegal-promotion-worker.service' \
  -v "$credential_dir":'/run/credentials/asklegal-promotion-worker.service':ro \
  -v '/etc/asklegal/trust/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro' \
  -v '/etc/asklegal/trust/vault-primary-ca.pem:/etc/asklegal/trust/vault-primary-ca.pem:ro' \
  -v '/etc/asklegal/trust/vault-recovery-ca.pem:/etc/asklegal/trust/vault-recovery-ca.pem:ro' \
  -v '/etc/asklegal/tls/internal-ca.crt:/etc/asklegal/tls/internal-ca.crt:ro' \
  'asklegal/promotion-worker:v1' >/dev/null

# Every network is attached before the process starts. Attaching after start
# is a race: the readiness gate can run before a dependency is reachable.
docker network connect --alias 'promotion-worker' 'asklegal-scheduler-promotion' "$container"
docker network connect --alias 'promotion-worker' 'asklegal-vault-primary' "$container"
docker network connect --alias 'promotion-worker' 'asklegal-vault-recovery' "$container"
docker network connect --alias 'promotion-worker' 'asklegal-telemetry' "$container"
docker network connect --alias 'promotion-worker' 'asklegal-egress-promotion' "$container"

# `docker start --attach` keeps this script in the foreground so systemd can
# supervise it; ExecStop stops the container itself.
exec docker start --attach "$container"
