#!/usr/bin/env bash
# Generated by tools/v1_poc_render_units.py. Do not edit by hand.
#
# Start sql-server exactly as it was proved to run.
set -euo pipefail

container='asklegal-sql-server'
runtime_uid=10001

# A stale container from a previous boot would keep the name and the old
# configuration, so the unit always starts from a clean one.
docker rm -f "$container" >/dev/null 2>&1 || true

# The secret reaches the container through the environment, never through
# argv: `docker -e NAME` with no value passes the variable through.
MSSQL_SA_PASSWORD="$(cat "$CREDENTIALS_DIRECTORY"/sql-bootstrap-password)"
export MSSQL_SA_PASSWORD

docker create \
  --name "$container" \
  --network 'asklegal-register' \
  --network-alias 'sql-server' \
  --user "$runtime_uid":"$runtime_uid" \
  --cap-drop ALL \
  --security-opt no-new-privileges \
  -e 'ACCEPT_EULA=Y' \
  -e 'MSSQL_PID=Developer' \
  -e 'MSSQL_SA_PASSWORD' \
  -v '/srv/asklegal/sql:/var/opt/mssql:rw' \
  -v '/etc/asklegal/tls/sql-server:/etc/asklegal/tls/sql-server:ro' \
  'mcr.microsoft.com/mssql/server@sha256:fa0dcf206087759fe6dad4cc02bfa88d97439085e548fbca9039330519c0cf1d' >/dev/null

# `docker start --attach` keeps this script in the foreground so systemd can
# supervise it; ExecStop stops the container itself.
exec docker start --attach "$container"
