#!/usr/bin/env bash
# Generated by tools/v1_poc_render_units.py. Do not edit by hand.
#
# Start vault-recovery exactly as it was proved to run.
set -euo pipefail

container='asklegal-vault-recovery'
runtime_uid=3009

# A stale container from a previous boot would keep the name and the old
# configuration, so the unit always starts from a clean one.
docker rm -f "$container" >/dev/null 2>&1 || true

# The secret reaches the container through the environment, never through
# argv: `docker -e NAME` with no value passes the variable through.
ROOT_ACCESS_KEY_ID="$(cat "$CREDENTIALS_DIRECTORY"/vault-recovery-root-access)"
export ROOT_ACCESS_KEY_ID
ROOT_SECRET_ACCESS_KEY="$(cat "$CREDENTIALS_DIRECTORY"/vault-recovery-root-secret)"
export ROOT_SECRET_ACCESS_KEY

docker create \
  --name "$container" \
  --network 'asklegal-vault-recovery' \
  --network-alias 'vault-recovery' \
  --user "$runtime_uid":"$runtime_uid" \
  --cap-drop ALL \
  --security-opt no-new-privileges \
  -e 'VGW_PORT=:7070' \
  -e 'VGW_CERT=/etc/asklegal/tls/vault-recovery/tls.crt' \
  -e 'VGW_KEY=/etc/asklegal/tls/vault-recovery/tls.key' \
  -e 'VGW_IAM_DIR=/vault/iam' \
  -e 'ROOT_ACCESS_KEY_ID' \
  -e 'ROOT_SECRET_ACCESS_KEY' \
  -v '/srv/asklegal/vault-recovery:/vault:rw' \
  -v '/etc/asklegal/tls/vault-recovery:/etc/asklegal/tls/vault-recovery:ro' \
  'ghcr.io/versity/versitygw@sha256:ef1c6bf0180abd9583da8a0466b3cba1cfc1ed368afebdf7280c0774081d2c82' \
  'posix' \
  '--versioning-dir' \
  '/vault/versions' \
  '--sidecar' \
  '/vault/sidecar' \
  '/vault/objects' >/dev/null

# `docker start --attach` keeps this script in the foreground so systemd can
# supervise it; ExecStop stops the container itself.
exec docker start --attach "$container"
