"""Typed SQL Server Management Register boundary."""

from asklegal_management_register.driver import (
    SqlCredentialError,
    SqlCredentialErrorCode,
    SqlServerPassword,
    V1MssqlAdminConnectionFactory,
    V1MssqlConnectionFactory,
)
from asklegal_management_register.local_legal_identity import LocalLegalIdentityRegister
from asklegal_management_register.store import (
    AmbiguousCommit,
    ApprovedPromotionClaim,
    ApprovedPromotionQueueStore,
    ClaimedEffect,
    CommandFingerprintMismatch,
    CommandResult,
    EffectHandoffStore,
    EffectReceiptRecord,
    ManagementRegisterStore,
    RecordedEffectReceipt,
    RegisteredApprovalConsumptionCommand,
    RegisteredApprovalLifecycleStore,
    RegisteredApprovalStore,
    RegisteredApprovalTerminalCommand,
    RegisteredExecutionAuthorizationCommand,
    RegisteredExecutionAuthorizationStore,
    RegisteredExecutionBeginCommand,
    RegisteredExecutionBeginStore,
    RegisterEventCommand,
    RegisterEventStore,
    RegisterProjectionError,
    ReviewReadyProposalRow,
    ServingStateCandidate,
    ServingStateReceipt,
    ServingStateStore,
    ServingStateVerificationError,
    V1CommandResult,
)

PACKAGE_ROLE: str = "management-register-adapter"

__all__ = [
    "PACKAGE_ROLE",
    "AmbiguousCommit",
    "ApprovedPromotionClaim",
    "ApprovedPromotionQueueStore",
    "ClaimedEffect",
    "CommandFingerprintMismatch",
    "CommandResult",
    "EffectHandoffStore",
    "EffectReceiptRecord",
    "LocalLegalIdentityRegister",
    "ManagementRegisterStore",
    "RecordedEffectReceipt",
    "RegisterEventCommand",
    "RegisterEventStore",
    "RegisterProjectionError",
    "RegisteredApprovalConsumptionCommand",
    "RegisteredApprovalLifecycleStore",
    "RegisteredApprovalStore",
    "RegisteredApprovalTerminalCommand",
    "RegisteredExecutionAuthorizationCommand",
    "RegisteredExecutionAuthorizationStore",
    "RegisteredExecutionBeginCommand",
    "RegisteredExecutionBeginStore",
    "ReviewReadyProposalRow",
    "ServingStateCandidate",
    "ServingStateReceipt",
    "ServingStateStore",
    "ServingStateVerificationError",
    "SqlCredentialError",
    "SqlCredentialErrorCode",
    "SqlServerPassword",
    "V1CommandResult",
    "V1MssqlAdminConnectionFactory",
    "V1MssqlConnectionFactory",
]
