"""Health, audit-signal, alert, and incident boundary."""

from .events import (
    OPERATIONAL_CATEGORY_ORDER,
    ObservabilityError,
    ObservabilityErrorCode,
    OperationalAlertCode,
    OperationalCategory,
    OperationalEmitter,
    OperationalEvent,
    OperationalEventCode,
    OperationalEventObservation,
    OperationalStatusScope,
    OperationalStreamSpec,
    alert_code_for,
    allowed_emitters,
    build_event_observation,
    build_operational_event,
    build_status_scope,
    build_stream_spec,
    clear_code_for,
    event_alert_code_for,
    serialize_operational_event,
)
from .status import (
    HKV1FamilyCycleResult,
    HKV1FamilyProgress,
    HKV1ProgressSnapshot,
    HKV1ProgressStatus,
    OperationalAlertProjection,
    OperationalStatusSnapshot,
    OperationalStreamStatus,
    aggregate_hk_v1_progress,
    aggregate_operational_status,
    parse_operational_status,
    serialize_hk_v1_progress,
    serialize_operational_status,
)

PACKAGE_ROLE: str = "observability"

__all__ = [
    "OPERATIONAL_CATEGORY_ORDER",
    "PACKAGE_ROLE",
    "HKV1FamilyCycleResult",
    "HKV1FamilyProgress",
    "HKV1ProgressSnapshot",
    "HKV1ProgressStatus",
    "ObservabilityError",
    "ObservabilityErrorCode",
    "OperationalAlertCode",
    "OperationalAlertProjection",
    "OperationalCategory",
    "OperationalEmitter",
    "OperationalEvent",
    "OperationalEventCode",
    "OperationalEventObservation",
    "OperationalStatusScope",
    "OperationalStatusSnapshot",
    "OperationalStreamSpec",
    "OperationalStreamStatus",
    "aggregate_hk_v1_progress",
    "aggregate_operational_status",
    "alert_code_for",
    "allowed_emitters",
    "build_event_observation",
    "build_operational_event",
    "build_status_scope",
    "build_stream_spec",
    "clear_code_for",
    "event_alert_code_for",
    "parse_operational_status",
    "serialize_hk_v1_progress",
    "serialize_operational_event",
    "serialize_operational_status",
]
