"""Immutable evidence package, vault, and recovery-copy boundary."""

from .local import (
    LocalImmutableVault,
    ManifestLastPackageWriter,
    RecoveryCopier,
    TwoVaultEvidenceReader,
)
from .model import (
    ArtifactClass,
    ArtifactDescriptor,
    CorruptEvidence,
    EvidenceError,
    EvidenceIntegrityIncident,
    EvidenceManifest,
    EvidenceManifestEntry,
    EvidencePackageReceipt,
    EvidenceReadReceipt,
    ExactObjectReference,
    HostileClassification,
    HostileReason,
    PackageIncomplete,
    RecoveryCopyReceipt,
    RetentionBlocked,
    RetentionProfile,
    VaultCollision,
    VaultName,
    VaultWriteReceipt,
    content_logical_key,
    manifest_logical_key,
    s3_provider_version_id,
    s3_version_reference,
    validate_logical_key,
)
from .ports import ImmutableVault
from .s3 import (
    S3AccessCredential,
    S3ImmutableVault,
    S3VaultError,
    S3VaultErrorCode,
    V1S3VaultSettings,
    create_exact_v1_s3_vault,
    create_v1_s3_client,
)

PACKAGE_ROLE: str = "evidence-vault"

__all__ = [
    "PACKAGE_ROLE",
    "ArtifactClass",
    "ArtifactDescriptor",
    "CorruptEvidence",
    "EvidenceError",
    "EvidenceIntegrityIncident",
    "EvidenceManifest",
    "EvidenceManifestEntry",
    "EvidencePackageReceipt",
    "EvidenceReadReceipt",
    "ExactObjectReference",
    "HostileClassification",
    "HostileReason",
    "ImmutableVault",
    "LocalImmutableVault",
    "ManifestLastPackageWriter",
    "PackageIncomplete",
    "RecoveryCopier",
    "RecoveryCopyReceipt",
    "RetentionBlocked",
    "RetentionProfile",
    "S3AccessCredential",
    "S3ImmutableVault",
    "S3VaultError",
    "S3VaultErrorCode",
    "TwoVaultEvidenceReader",
    "V1S3VaultSettings",
    "VaultCollision",
    "VaultName",
    "VaultWriteReceipt",
    "content_logical_key",
    "create_exact_v1_s3_vault",
    "create_v1_s3_client",
    "manifest_logical_key",
    "s3_provider_version_id",
    "s3_version_reference",
    "validate_logical_key",
]
