"""Approval-bound serving promotion rules and local conformance adapters."""

from .builder import (
    embedding_request,
    freeze_embedding_profile,
    freeze_promotion_manifest,
    pinecone_index_name,
    verify_embedding_profile,
    verify_promotion_manifest,
)
from .local import (
    LocalBackupStore,
    LocalCoverageStore,
    LocalEmbeddingAdapter,
    LocalFailurePlan,
    LocalRoutingStore,
    LocalServingTargetStore,
    OutcomeUnknown,
)
from .model import (
    BackupVerification,
    EmbeddedVector,
    EmbeddingProfile,
    EmbeddingProfileInput,
    EmbeddingReceipt,
    EmbeddingRequest,
    EmbeddingRequestInput,
    PromotionError,
    PromotionErrorCode,
    PromotionExecutionResult,
    PromotionManifest,
    PromotionPlan,
    TargetDefinition,
    TargetRecord,
)
from .ports import BackupPort, CoveragePort, EmbeddingPort, RoutingPort, ServingTargetPort
from .remote import (
    AZURE_OPENAI_PROVIDER,
    AzureOpenAIConfig,
    AzureOpenAIEmbeddingAdapter,
    AzureOpenAIGenerativeAdapter,
    PineconeConfig,
    PineconeServingTargetStore,
    ProviderResponse,
    ProviderTransport,
    target_state_fingerprint,
)

PACKAGE_ROLE: str = "promotion"

__all__ = [
    "AZURE_OPENAI_PROVIDER",
    "PACKAGE_ROLE",
    "AzureOpenAIConfig",
    "AzureOpenAIEmbeddingAdapter",
    "AzureOpenAIGenerativeAdapter",
    "BackupPort",
    "BackupVerification",
    "CoveragePort",
    "EmbeddedVector",
    "EmbeddingPort",
    "EmbeddingProfile",
    "EmbeddingProfileInput",
    "EmbeddingReceipt",
    "EmbeddingRequest",
    "EmbeddingRequestInput",
    "LocalBackupStore",
    "LocalCoverageStore",
    "LocalEmbeddingAdapter",
    "LocalFailurePlan",
    "LocalRoutingStore",
    "LocalServingTargetStore",
    "OutcomeUnknown",
    "PineconeConfig",
    "PineconeServingTargetStore",
    "PromotionError",
    "PromotionErrorCode",
    "PromotionExecutionResult",
    "PromotionManifest",
    "PromotionPlan",
    "ProviderResponse",
    "ProviderTransport",
    "RoutingPort",
    "ServingTargetPort",
    "TargetDefinition",
    "TargetRecord",
    "embedding_request",
    "freeze_embedding_profile",
    "freeze_promotion_manifest",
    "pinecone_index_name",
    "target_state_fingerprint",
    "verify_embedding_profile",
    "verify_promotion_manifest",
]
