"""Approval-bound serving promotion rules and local conformance adapters."""

from .builder import (
    SERVING_METADATA_KEYS,
    embedding_request,
    freeze_embedding_profile,
    freeze_promotion_manifest,
    freeze_v1_promotion_manifest,
    pinecone_index_name,
    promotion_approval_snapshot_from_bytes,
    promotion_manifest_bytes,
    proposal_receipt_document,
    proposal_receipt_fingerprint,
    serving_metadata,
    serving_metadata_fingerprint,
    stored_proposal_package_from_bytes,
    verify_embedding_profile,
    verify_promotion_manifest,
    verify_stored_proposal_package,
)
from .local import (
    LocalBackupStore,
    LocalCoverageStore,
    LocalEmbeddingAdapter,
    LocalFailurePlan,
    LocalRoutingStore,
    LocalServingTargetStore,
)
from .model import (
    BackupVerification,
    EmbeddedVector,
    EmbeddingProfile,
    EmbeddingProfileInput,
    EmbeddingReceipt,
    EmbeddingRequest,
    EmbeddingRequestInput,
    OutcomeUnknown,
    PromotionApprovalSnapshot,
    PromotionError,
    PromotionErrorCode,
    PromotionExecutionResult,
    PromotionManifest,
    PromotionPlan,
    ProposalMemberReceipt,
    StoredProposalPackage,
    TargetDefinition,
    TargetRecord,
)
from .ports import BackupPort, CoveragePort, EmbeddingPort, RoutingPort, ServingTargetPort
from .proposal import read_stored_proposal_package
from .remote import (
    AZURE_OPENAI_PROVIDER,
    AzureOpenAIConfig,
    AzureOpenAIEmbeddingAdapter,
    AzureOpenAIGenerativeAdapter,
    PineconeConfig,
    PineconeServingTargetStore,
    ProviderResponse,
    ProviderTransport,
    target_state_fingerprint,
)

PACKAGE_ROLE: str = "promotion"

__all__ = [
    "AZURE_OPENAI_PROVIDER",
    "PACKAGE_ROLE",
    "SERVING_METADATA_KEYS",
    "AzureOpenAIConfig",
    "AzureOpenAIEmbeddingAdapter",
    "AzureOpenAIGenerativeAdapter",
    "BackupPort",
    "BackupVerification",
    "CoveragePort",
    "EmbeddedVector",
    "EmbeddingPort",
    "EmbeddingProfile",
    "EmbeddingProfileInput",
    "EmbeddingReceipt",
    "EmbeddingRequest",
    "EmbeddingRequestInput",
    "LocalBackupStore",
    "LocalCoverageStore",
    "LocalEmbeddingAdapter",
    "LocalFailurePlan",
    "LocalRoutingStore",
    "LocalServingTargetStore",
    "OutcomeUnknown",
    "PineconeConfig",
    "PineconeServingTargetStore",
    "PromotionApprovalSnapshot",
    "PromotionError",
    "PromotionErrorCode",
    "PromotionExecutionResult",
    "PromotionManifest",
    "PromotionPlan",
    "ProposalMemberReceipt",
    "ProviderResponse",
    "ProviderTransport",
    "RoutingPort",
    "ServingTargetPort",
    "StoredProposalPackage",
    "TargetDefinition",
    "TargetRecord",
    "embedding_request",
    "freeze_embedding_profile",
    "freeze_promotion_manifest",
    "freeze_v1_promotion_manifest",
    "pinecone_index_name",
    "promotion_approval_snapshot_from_bytes",
    "promotion_manifest_bytes",
    "proposal_receipt_document",
    "proposal_receipt_fingerprint",
    "read_stored_proposal_package",
    "serving_metadata",
    "serving_metadata_fingerprint",
    "stored_proposal_package_from_bytes",
    "target_state_fingerprint",
    "verify_embedding_profile",
    "verify_promotion_manifest",
    "verify_stored_proposal_package",
]
