"""Render the root provisioning scripts for the V1 POC host from the contracts.

The scripts are generated, never hand-written, so they cannot drift from
`host_admission_policy.json`, `host_identity_inputs.json`, `topology.json`, and
`systemd_unit_inputs.json`. `--check` re-renders and compares, so a hand edit or
an unpropagated contract change fails the ordinary test suite.

What the scripts do is deliberately narrow. They create storage, accounts,
directories, container networks, and journal settings. They install no unit,
enable no service, pull no image, and create no credential: those stay behind
their own gates.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

OUTPUT_ROOT = Path("infrastructure/poc/provisioning")
HOST_POLICY_PATH = Path("infrastructure/poc/host_admission_policy.json")
IDENTITY_PATH = Path("infrastructure/poc/host_identity_inputs.json")
TOPOLOGY_PATH = Path("infrastructure/poc/topology.json")
SYSTEMD_PATH = Path("infrastructure/poc/systemd_unit_inputs.json")

_DATA_DISK_UUID = "3667a2bf-a59b-485c-b07a-2150c1a18d63"
_DATA_MOUNTPOINT = "/srv/asklegal"
_SQL_IMAGE_UID = 10001
_DIRECTORY_MODE = "0750"
_GENERATED = "# Generated by tools/v1_poc_render_provisioning.py. Do not edit by hand."

_HEADER = """#!/usr/bin/env bash
{generated}
#
# {title}
#
set -euo pipefail

DRY_RUN="${{DRY_RUN:-0}}"

run() {{
  if [ "$DRY_RUN" = "1" ]; then
    printf '  would run: %s\\n' "$*"
  else
    "$@"
  fi
}}

note() {{ printf '%s\\n' "$*"; }}

require_root() {{
  if [ "$(id -u)" -ne 0 ] && [ "$DRY_RUN" != "1" ]; then
    note "this step must run as root; re-run with sudo, or set DRY_RUN=1 to preview"
    exit 1
  fi
}}
"""


def _read(root: Path, path: Path) -> dict[str, object]:
    value = json.loads((root / path).read_bytes())
    if not isinstance(value, dict):
        message = f"provisioning input root: {path}"
        raise TypeError(message)
    return value


def _objects(value: object) -> list[dict[str, object]]:
    if not isinstance(value, list):
        message = "provisioning object list"
        raise TypeError(message)
    return [item for item in value if isinstance(item, dict)]


def _preflight(host_policy: dict[str, object]) -> str:
    runtime = host_policy["runtime"]
    if not isinstance(runtime, dict):
        message = "runtime policy"
        raise TypeError(message)
    locks = runtime["host_package_locks"]
    if not isinstance(locks, dict):
        message = "host package locks"
        raise TypeError(message)
    checks = "\n".join(
        f'check_package {name} "{version}"' for name, version in sorted(locks.items())
    )
    return (
        _HEADER.format(generated=_GENERATED, title="Step 10 — read-only preflight")
        + f"""
# Reads only. Changes nothing. Run this first and read the output.

failures=0

fail() {{ note "  FAIL  $*"; failures=$((failures + 1)); }}
pass() {{ note "  ok    $*"; }}

check_package() {{
  local name="$1" expected="$2" actual
  actual="$(dpkg-query --showformat='${{Version}}' --show "$name" 2>/dev/null || true)"
  if [ "$actual" = "$expected" ]; then pass "$name $expected"; else
    fail "$name expected $expected, found ${{actual:-NOT_INSTALLED}}"
  fi
}}

note "operating system"
if [ "$(. /etc/os-release && printf '%s %s' "$ID" "$VERSION_ID")" = "ubuntu 24.04" ]; then
  pass "ubuntu 24.04"
else
  fail "expected ubuntu 24.04"
fi
if [ "$(uname -m)" = "x86_64" ]; then pass "x86_64"; else fail "expected x86_64"; fi

note "locked host packages"
{checks}

note "data disk"
if blkid -U "{_DATA_DISK_UUID}" >/dev/null 2>&1; then
  pass "disk {_DATA_DISK_UUID} present"
else
  fail "disk {_DATA_DISK_UUID} not found"
fi

note "credential protection"
if systemd-creds has-tpm2 >/dev/null 2>&1; then
  pass "TPM2 available for systemd-creds"
else
  note "  note  no TPM2; HOST_KEY_ONLY protection would apply"
fi

note "numeric identities are free"
allocated="3000 3001 3002 3003 3004 3005 3006 3007 3008 3009"
reserved="3010 3011 3012 3013 3014 {_SQL_IMAGE_UID}"
for id in $allocated $reserved; do
  if getent passwd "$id" >/dev/null || getent group "$id" >/dev/null; then
    existing="$(getent passwd "$id" | cut -d: -f1)"
    case "$existing" in
      asklegal-*) pass "$id already held by $existing" ;;
      *) fail "$id is taken by ${{existing:-a group}}" ;;
    esac
  else
    pass "$id free"
  fi
done

note ""
if [ "$failures" -eq 0 ]; then
  note "preflight passed; nothing was changed"
else
  note "preflight found $failures problem(s); do not continue until they are resolved"
  exit 1
fi
"""
    )


def _storage() -> str:
    return (
        _HEADER.format(generated=_GENERATED, title="Step 20 — mount the data disk at /srv/asklegal")
        + f"""
# The three evidence and database paths must sit on one ext4 disk at a stable
# system path. The 4.0 TB disk is currently auto-mounted by the desktop session
# under /media, which is not a stable location for a service. This moves it to
# {_DATA_MOUNTPOINT} through /etc/fstab, by UUID.
#
# Recovery stays LOGICALLY_SEPARATE_POC_RECOVERY: both vaults share this disk,
# so losing it loses both. That limitation is accepted and unchanged here.

require_root

UUID="{_DATA_DISK_UUID}"
MOUNTPOINT="{_DATA_MOUNTPOINT}"
FSTAB_LINE="UUID=$UUID $MOUNTPOINT ext4 defaults,noatime,nofail 0 2"

if ! blkid -U "$UUID" >/dev/null 2>&1; then
  note "disk $UUID not found; refusing to continue"
  exit 1
fi

current="$(findmnt --noheadings --output TARGET --source "/dev/disk/by-uuid/$UUID" || true)"
if [ -n "$current" ] && [ "$current" != "$MOUNTPOINT" ]; then
  note "unmounting the desktop automount at $current"
  run umount "$current"
fi

run mkdir -p "$MOUNTPOINT"

if grep -q "UUID=$UUID" /etc/fstab; then
  note "fstab already references $UUID"
else
  note "adding the fstab entry"
  if [ "$DRY_RUN" = "1" ]; then
    printf '  would append: %s\\n' "$FSTAB_LINE"
  else
    cp /etc/fstab "/etc/fstab.asklegal-backup.$(date +%s)"
    printf '%s\\n' "$FSTAB_LINE" >> /etc/fstab
  fi
fi

run systemctl daemon-reload
if ! findmnt --mountpoint "$MOUNTPOINT" >/dev/null 2>&1; then
  run mount "$MOUNTPOINT"
fi

if [ "$DRY_RUN" != "1" ]; then
  findmnt --mountpoint "$MOUNTPOINT" --output SOURCE,FSTYPE,SIZE,TARGET
fi
run chown root:root "$MOUNTPOINT"
run chmod 0755 "$MOUNTPOINT"
note "storage ready"
"""
    )


def _identities(identity_policy: dict[str, object], topology: dict[str, object]) -> str:
    profile = identity_policy["identity_profile"]
    if not isinstance(profile, dict):
        message = "identity profile"
        raise TypeError(message)
    lines: list[str] = []
    for entry in sorted(
        _objects(identity_policy["identities"]), key=lambda item: str(item["identity"])
    ):
        name = str(entry["identity"])
        number = entry["uid"]
        lines.append(f'create_identity "{name}" {number}')
    owner_by_path: dict[str, str] = {}
    for service in _objects(topology["services"]):
        service_id = str(service["service_id"])
        identity = str(service["identity"])
        for path in service["write_paths"] if isinstance(service["write_paths"], list) else []:
            owner_by_path[str(path)] = (
                f"{_SQL_IMAGE_UID}:{_SQL_IMAGE_UID}"
                if service_id == "sql-server"
                else f"{identity}:{identity}"
            )
    directories = [
        f'create_directory "{path}" "{owner_by_path[path]}"' for path in sorted(owner_by_path)
    ]
    return (
        _HEADER.format(generated=_GENERATED, title="Step 30 — host accounts and owned directories")
        + f"""
# Ten locked, non-login service accounts with the exact numeric identities the
# contract allocated, plus the fourteen directories they own.
#
# The numbers are not free choices. systemd's LoadCredential writes a 0400 file
# owned by the unit account, so each container must run under the same numeric
# UID or it cannot read its own credential. SQL Server keeps its image-defined
# {_SQL_IMAGE_UID}, which is a fact read from the pinned image.

require_root

create_identity() {{
  local name="$1" number="$2"
  if getent group "$name" >/dev/null; then
    local existing_gid
    existing_gid="$(getent group "$name" | cut -d: -f3)"
    if [ "$existing_gid" != "$number" ]; then
      note "group $name exists with gid $existing_gid, expected $number; refusing"
      exit 1
    fi
  else
    run groupadd --system --gid "$number" "$name"
  fi
  if getent passwd "$name" >/dev/null; then
    local existing_uid
    existing_uid="$(getent passwd "$name" | cut -d: -f3)"
    if [ "$existing_uid" != "$number" ]; then
      note "user $name exists with uid $existing_uid, expected $number; refusing"
      exit 1
    fi
    note "  identity $name already correct"
  else
    run useradd --system --uid "$number" --gid "$number" \\
      --home-dir "{profile["home_directory"]}" --no-create-home \\
      --shell "{profile["login_shell"]}" "$name"
    run passwd --lock "$name"
  fi
}}

create_directory() {{
  local path="$1" owner="$2"
  run install -d -o "${{owner%%:*}}" -g "${{owner##*:}}" -m {_DIRECTORY_MODE} "$path"
}}

note "service accounts"
{chr(10).join(lines)}

note "owned directories"
run install -d -o root -g root -m 0755 /var/lib/asklegal
{chr(10).join(directories)}

note "trust and configuration directories"
run install -d -o root -g root -m 0755 /etc/asklegal
run install -d -o root -g root -m 0755 /etc/asklegal/tls

note "identities and directories ready; no service was enabled"
"""
    )


def _networks(systemd_policy: dict[str, object]) -> str:
    lines: list[str] = []
    for network in _objects(systemd_policy["container_networks"]):
        network_id = str(network["network_id"])
        subnet = str(network["subnet"])
        internal = "internal" if network["internal"] is True else "routable"
        lines.append(f'create_network "{network_id}" "{subnet}" {internal}')
    return (
        _HEADER.format(generated=_GENERATED, title="Step 40 — private container networks")
        + f"""
# Ten networks on collision-free /24 subnets from 10.90.0.0/16, chosen to avoid
# this host's LAN, VPN, and Docker's own bridge and default pool.
#
# Seven are internal: Docker gives them no route off the host at all. The three
# egress networks are routable because the proxy on each one has to reach its
# allowlisted destinations. That means a worker attached to an egress network
# also has a route out, which Docker alone does not restrict — see the note at
# the end of this file.

require_root

create_network() {{
  local name="$1" subnet="$2" isolation="$3"
  if docker network inspect "$name" >/dev/null 2>&1; then
    local existing
    local format='{{{{range .IPAM.Config}}}}{{{{.Subnet}}}}{{{{end}}}}'
    existing="$(docker network inspect --format "$format" "$name")"
    if [ "$existing" != "$subnet" ]; then
      note "network $name exists on $existing, expected $subnet; refusing"
      exit 1
    fi
    note "  network $name already correct"
    return
  fi
  if [ "$isolation" = "internal" ]; then
    run docker network create --driver bridge --internal --subnet "$subnet" "$name"
  else
    run docker network create --driver bridge --subnet "$subnet" "$name"
  fi
}}

{chr(10).join(lines)}

note "container networks ready"
note ""
note "OPEN ITEM — per-container egress is not yet enforced."
note "The accepted topology gives acquisition, legal-processing, and promotion an"
note "outbound profile of OFFICIAL_SOURCE_ONLY, MODEL_PROVIDER_ONLY, and"
note "PINECONE_AND_EMBEDDING_ONLY. Docker cannot express that on its own: on a"
note "routable network every member can reach outside, not just the proxy."
note "Closing it needs a decision: either give each proxy a fixed address and"
note "restrict the subnet in Docker's DOCKER-USER chain, or dual-home each proxy"
note "so the worker sits only on an internal network. Neither is applied here."
"""
    )


def _journal_time() -> str:
    return (
        _HEADER.format(generated=_GENERATED, title="Step 50 — persistent sealed journal and time")
        + """
# Host admission requires a persistent, forward-secure-sealed journal and working
# time synchronization. Sealing needs a key pair; this generates one if absent.

require_root

CONF=/etc/systemd/journald.conf.d/asklegal.conf

run install -d -o root -g root -m 0755 /etc/systemd/journald.conf.d
if [ "$DRY_RUN" = "1" ]; then
  printf '  would write: %s\\n' "$CONF"
else
  cat > "$CONF" <<'CONFEOF'
# Generated by tools/v1_poc_render_provisioning.py. Do not edit by hand.
[Journal]
Storage=persistent
Seal=yes
CONFEOF
fi

run systemctl restart systemd-journald

sealing_key_present() {
  compgen -G "/var/log/journal/*/fss" > /dev/null 2>&1
}

if [ "$DRY_RUN" = "1" ]; then
  note "  would generate the forward-secure sealing key if absent"
elif sealing_key_present; then
  note "forward-secure sealing key already present"
else
  note "generating the forward-secure sealing key"
  note "this prints a verification key once; write it down, it is not stored here"
  journalctl --setup-keys --interval=1day || note "sealing key setup reported a problem"
fi

if timedatectl show --property=NTP --value | grep -q '^yes$'; then
  note "time synchronization already enabled"
else
  run timedatectl set-ntp true
fi

note "journal and time ready"
"""
    )


def _firewall() -> str:
    return (
        _HEADER.format(generated=_GENERATED, title="Step 60 — host input firewall (RUN SEPARATELY)")
        + """
# ============================ READ THIS FIRST ============================
#
# This is the one step that can lock you out of this machine. It sets a
# default-deny policy on inbound host traffic. If you administer this host over
# SSH, applying it will drop your session and you will need physical access.
#
# provision.sh does NOT run this. Run it deliberately, at the console.
#
# It adds one separate nftables table, `inet asklegal`. It does not touch the
# filter FORWARD path, because Docker manages that and overriding it would break
# container networking. Container isolation comes from the internal networks
# created in step 40 instead.
#
# To undo everything this does:   nft delete table inet asklegal
#
# A dead-man timer is armed by default: unless you confirm within the timeout,
# the rules are removed automatically.
# =========================================================================

require_root

CONFIRM_SECONDS="${CONFIRM_SECONDS:-120}"
SKIP_DEADMAN="${SKIP_DEADMAN:-0}"

if [ "${I_HAVE_CONSOLE_ACCESS:-0}" != "1" ] && [ "$DRY_RUN" != "1" ]; then
  note "refusing to apply an input default-deny policy without confirmation."
  note "re-run as: I_HAVE_CONSOLE_ACCESS=1 $0"
  exit 1
fi

apply_rules() {
  nft -f - <<'NFTEOF'
table inet asklegal {
  chain input {
    type filter hook input priority filter; policy drop;
    ct state established,related accept
    ct state invalid drop
    iif lo accept
    ip protocol icmp accept
    ip6 nexthdr ipv6-icmp accept
  }
}
NFTEOF
}

if [ "$DRY_RUN" = "1" ]; then
  note "would add nftables table inet asklegal with an input default-deny policy"
  note "would arm a ${CONFIRM_SECONDS}s dead-man revert"
  exit 0
fi

if [ "$SKIP_DEADMAN" != "1" ]; then
  note "arming a ${CONFIRM_SECONDS}s dead-man revert"
  setsid bash -c "sleep $CONFIRM_SECONDS; \\
    if [ ! -f /run/asklegal-firewall-confirmed ]; then \\
      nft delete table inet asklegal 2>/dev/null || true; \\
    fi" >/dev/null 2>&1 &
fi

apply_rules
note "input default-deny applied. Public TCP ports: none, as the policy requires."
note ""
note "Confirm within ${CONFIRM_SECONDS}s to keep it:"
note "  touch /run/asklegal-firewall-confirmed"
note "Otherwise it reverts by itself. To remove it now:"
note "  nft delete table inet asklegal"
"""
    )


def _top_level() -> str:
    return (
        _HEADER.format(generated=_GENERATED, title="V1 POC host provisioning")
        + """
# Runs steps 10 through 50 in order. Step 60, the firewall, is deliberately not
# run here: it can lock you out and must be run on its own, at the console.
#
# Preview everything without changing anything:   DRY_RUN=1 ./provision.sh
#
# This installs no systemd unit, enables no service, pulls no image, and creates
# no credential. Those remain behind their own gates.

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

for step in 10-preflight 20-storage 30-identities 40-networks 50-journal-time; do
  note ""
  note "=== $step ==="
  DRY_RUN="$DRY_RUN" bash "$HERE/$step.sh"
done

note ""
note "=== done ==="
note "host storage, identities, directories, networks, journal, and time are ready."
note "Not done here, on purpose:"
note "  - step 60 firewall (run it yourself, at the console)"
note "  - internal TLS certificates for SQL, both vaults, and Review"
note "  - systemd units, image pulls, credentials, and service enablement"
"""
    )


def render(root: Path) -> dict[str, str]:
    """Render every provisioning script from the current contracts."""
    host_policy = _read(root, HOST_POLICY_PATH)
    identity_policy = _read(root, IDENTITY_PATH)
    topology = _read(root, TOPOLOGY_PATH)
    systemd_policy = _read(root, SYSTEMD_PATH)
    return {
        "provision.sh": _top_level(),
        "10-preflight.sh": _preflight(host_policy),
        "20-storage.sh": _storage(),
        "30-identities.sh": _identities(identity_policy, topology),
        "40-networks.sh": _networks(systemd_policy),
        "50-journal-time.sh": _journal_time(),
        "60-firewall.sh": _firewall(),
    }


def write(root: Path) -> tuple[str, ...]:
    """Write every rendered script and make it executable."""
    output = root / OUTPUT_ROOT
    output.mkdir(parents=True, exist_ok=True)
    for name, content in sorted(render(root).items()):
        path = output / name
        path.write_text(content, encoding="utf-8")
        path.chmod(0o755)
    return tuple(sorted(render(root)))


def check(root: Path) -> tuple[str, ...]:
    """Return the names of scripts that differ from the current contracts."""
    output = root / OUTPUT_ROOT
    drifted: list[str] = []
    for name, content in sorted(render(root).items()):
        path = output / name
        if not path.is_file() or path.read_text(encoding="utf-8") != content:
            drifted.append(name)
    return tuple(drifted)


def main() -> None:
    """Render the provisioning scripts, or verify that they match the contracts."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify instead of writing")
    arguments = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    if arguments.check:
        drifted = check(root)
        if drifted:
            message = f"provisioning scripts differ from the contracts: {', '.join(drifted)}"
            raise ValueError(message)
        print("PASS V1 POC provisioning scripts match the contracts")  # noqa: T201
        return
    names = write(root)
    print(f"rendered {len(names)} provisioning scripts into {OUTPUT_ROOT}")  # noqa: T201


if __name__ == "__main__":
    main()
