"""Render the V1 POC systemd units and their launchers from the contracts.

Like the provisioning scripts, these files are generated and never hand-written,
so they cannot drift from `service_runtime_commands.json`, `topology.json`,
`host_identity_inputs.json`, and `systemd_unit_inputs.json`. `--check` re-renders
and compares, so a hand edit or an unpropagated contract change fails the
ordinary test suite.

Two things shape every unit here.

Credentials never touch persistent plaintext. systemd decrypts each one into the
unit's own `$CREDENTIALS_DIRECTORY`, which is a tmpfs owned by root. The five
applications need a directory of files owned by their own runtime uid at mode
0400, so each launcher copies them into `/run/asklegal/credentials/<service>` with
that exact ownership before starting the container. The infrastructure images take
their secrets from the environment instead; the launcher exports the value and
passes the bare variable name to `docker`, so no secret ever appears in argv.

Nothing here is admitted. The units are rendered disabled, the five application
images are still local tags rather than digests, and installation, credential
sealing, and enablement are all separate root steps the user runs deliberately.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

OUTPUT_ROOT = Path("infrastructure/poc/units")
RUNTIME_COMMANDS_PATH = Path("infrastructure/poc/service_runtime_commands.json")
SYSTEMD_PATH = Path("infrastructure/poc/systemd_unit_inputs.json")

_GENERATED = "# Generated by tools/v1_poc_render_units.py. Do not edit by hand."
_CREDENTIAL_ROOT = "/run/asklegal/credentials"
_LAUNCH_ROOT = "/etc/asklegal/launch"
_CONFIG_ROOT = "/etc/asklegal/config"
_SEALED_ROOT = "/etc/asklegal/credentials"
_STOP_SECONDS = 30
_TIMEOUT_STOP_SECONDS = 45


class UnitRenderError(RuntimeError):
    """One exact, secret-free unit rendering failure."""


def _read(root: Path, path: Path) -> dict[str, object]:
    value = json.loads((root / path).read_bytes())
    if not isinstance(value, dict):
        message = f"unit input root: {path}"
        raise UnitRenderError(message)
    return value


def _objects(value: object) -> list[dict[str, object]]:
    if not isinstance(value, list):
        message = "unit object list"
        raise UnitRenderError(message)
    return [item for item in value if isinstance(item, dict)]


def _strings(value: object) -> list[str]:
    if not isinstance(value, list):
        return []
    return [str(item) for item in value]


def _quote(value: str) -> str:
    """Quote one argument for a generated shell script."""
    return "'" + value.replace("'", "'\\''") + "'"


def _dependency_units(systemd_policy: dict[str, object]) -> dict[str, list[str]]:
    """Map each unit name to the units the accepted contract says it requires."""
    ordering: dict[str, list[str]] = {}
    for group in ("service_units", "bootstrap_units"):
        for unit in _objects(systemd_policy.get(group)):
            name = str(unit.get("unit_name", ""))
            if not name:
                continue
            ordering[name] = _strings(unit.get("requires"))
    return ordering


def _unit_file(service: dict[str, object], requires: list[str]) -> str:
    """Render one hardened service unit for an already-proven container."""
    service_id = str(service["service_id"])
    unit_name = str(service["unit_name"])
    ordering = ["docker.service", "asklegal-networks.service", *requires]
    lines = [
        _GENERATED,
        "[Unit]",
        f"Description=AskLegal V1 POC {service_id}",
        f"Requires={' '.join(ordering)}",
        f"After={' '.join(ordering)}",
        "PartOf=asklegal.target",
        "",
        "[Service]",
        "Type=simple",
        "Restart=on-failure",
        "RestartSec=5",
        "NoNewPrivileges=true",
        "ProtectSystem=strict",
        "ProtectHome=true",
        "PrivateTmp=true",
        "CapabilityBoundingSet=",
        "ReadWritePaths=/run/asklegal",
    ]
    # Sealed to this host's TPM; systemd decrypts into $CREDENTIALS_DIRECTORY,
    # which is a tmpfs and disappears when the unit stops.
    lines.extend(
        f"LoadCredentialEncrypted={name}:{_SEALED_ROOT}/{name}.cred"
        for name in _strings(service.get("credential_names"))
    )
    lines += [
        f"ExecStart={_LAUNCH_ROOT}/{service_id}.sh",
        f"ExecStop=/usr/bin/docker stop --time={_STOP_SECONDS} asklegal-{service_id}",
        f"TimeoutStopSec={_TIMEOUT_STOP_SECONDS}",
        "",
        "[Install]",
        "WantedBy=multi-user.target",
        "",
    ]
    if not unit_name.endswith(".service"):
        message = f"unit name must be a service: {unit_name}"
        raise UnitRenderError(message)
    return "\n".join(lines)


def _credential_preamble(service: dict[str, object]) -> list[str]:
    """Render the lines that put this service's credentials where it expects them."""
    service_id = str(service["service_id"])
    delivery = str(service.get("credential_delivery", "NONE"))
    if delivery == "DIRECTORY_OWNED_BY_RUNTIME_UID":
        body = [
            "# The application reads its own credentials as files owned by its runtime",
            "# uid at mode 0400. $CREDENTIALS_DIRECTORY is root-owned, so copy rather",
            "# than mount it, onto /run, which is a tmpfs.",
            f"credential_dir={_quote(f'{_CREDENTIAL_ROOT}/{service_id}')}",
            'rm -rf "$credential_dir"',
            'mkdir -p "$credential_dir"',
        ]
        body.extend(
            f'install -o "$runtime_uid" -g "$runtime_uid" -m 0400 '
            f'"$CREDENTIALS_DIRECTORY"/{name} "$credential_dir"/{name}'
            for name in _strings(service.get("credential_names"))
        )
        return [*body, 'chown "$runtime_uid":"$runtime_uid" "$credential_dir"',
                'chmod 0500 "$credential_dir"', ""]
    if delivery == "ENVIRONMENT_FROM_LOADED_CREDENTIAL":
        body = [
            "# The secret reaches the container through the environment, never through",
            "# argv: `docker -e NAME` with no value passes the variable through.",
        ]
        for entry in _objects(service.get("credential_environment")):
            variable = str(entry["variable"])
            name = str(entry["credential"])
            body.append(f'{variable}="$(cat "$CREDENTIALS_DIRECTORY"/{name})"')
            body.append(f"export {variable}")
        return [*body, ""]
    return []


def _create_arguments(service: dict[str, object]) -> list[str]:
    """Render the exact `docker create` argument list for one proven service."""
    unit_name = str(service["unit_name"])
    first = _objects(service["networks"])[0]
    create = [
        "docker create",
        '  --name "$container"',
        f"  --network {_quote(str(first['network']))}",
        f"  --network-alias {_quote(str(first['alias']))}",
        '  --user "$runtime_uid":"$runtime_uid"',
        "  --cap-drop ALL",
        "  --security-opt no-new-privileges",
    ]
    if service.get("read_only_root") is True:
        create.append("  --read-only")
    create.extend(
        f"  --tmpfs {_quote(str(entry['target']))}"
        f":uid=$runtime_uid,gid=$runtime_uid,mode={entry.get('mode', '0700')}"
        for entry in _objects(service.get("tmpfs"))
    )
    create.extend(
        f"  -e {_quote(str(entry['name']) + '=' + str(entry['value']))}"
        for entry in _objects(service.get("environment"))
    )
    create.extend(
        f"  -e {_quote(str(entry['variable']))}"
        for entry in _objects(service.get("credential_environment"))
    )
    if str(service.get("credential_delivery")) == "DIRECTORY_OWNED_BY_RUNTIME_UID":
        target = f"/run/credentials/{unit_name}"
        create.append(f"  -e {_quote(f'CREDENTIALS_DIRECTORY={target}')}")
        create.append(f'  -v "$credential_dir":{_quote(target)}:ro')
    create.extend(
        f"  -v {_quote(f'{entry["source"]}:{entry["target"]}:{entry.get("mode", "ro")}')}"
        for entry in _objects(service.get("mounts"))
    )
    create.append(f"  {_quote(str(service['image']))}")
    create.extend(f"  {_quote(argument)}" for argument in _strings(service.get("command")))
    return create


def _launcher(service: dict[str, object]) -> str:
    """Render the launcher that turns one contract entry into a running container."""
    service_id = str(service["service_id"])
    uid = service["runtime_uid"]
    if type(uid) is not int:
        message = f"runtime uid for {service_id}"
        raise UnitRenderError(message)
    networks = _objects(service.get("networks"))
    if not networks:
        message = f"no network for {service_id}"
        raise UnitRenderError(message)

    body = [
        "#!/usr/bin/env bash",
        _GENERATED,
        "#",
        f"# Start {service_id} exactly as it was proved to run.",
        "set -euo pipefail",
        "",
        f"container={_quote(f'asklegal-{service_id}')}",
        f"runtime_uid={uid}",
        "",
        "# A stale container from a previous boot would keep the name and the old",
        "# configuration, so the unit always starts from a clean one.",
        'docker rm -f "$container" >/dev/null 2>&1 || true',
        "",
        *_credential_preamble(service),
        " \\\n".join(_create_arguments(service)) + " >/dev/null",
        "",
    ]
    if len(networks) > 1:
        body += [
            "# Every network is attached before the process starts. Attaching after start",
            "# is a race: the readiness gate can run before a dependency is reachable.",
        ]
        body.extend(
            f"docker network connect --alias {_quote(str(entry['alias']))} "
            f'{_quote(str(entry["network"]))} "$container"'
            for entry in networks[1:]
        )
        body.append("")
    body += [
        "# `docker start --attach` keeps this script in the foreground so systemd can",
        "# supervise it; ExecStop stops the container itself.",
        'exec docker start --attach "$container"',
        "",
    ]
    return "\n".join(body)


def _networks_unit() -> str:
    """Render the bootstrap unit that guarantees the ten networks exist."""
    return "\n".join(
        [
            _GENERATED,
            "[Unit]",
            "Description=AskLegal V1 POC container networks",
            "Requires=docker.service",
            "After=docker.service",
            "",
            "[Service]",
            "Type=oneshot",
            "RemainAfterExit=true",
            "NoNewPrivileges=true",
            "ProtectSystem=strict",
            "ProtectHome=true",
            f"ExecStart={_LAUNCH_ROOT}/networks.sh",
            "",
            "[Install]",
            "WantedBy=multi-user.target",
            "",
        ]
    )


def _networks_launcher(systemd_policy: dict[str, object]) -> str:
    """Render the idempotent network creation the bootstrap unit runs."""
    body = [
        "#!/usr/bin/env bash",
        _GENERATED,
        "#",
        "# Create any missing V1 network. Existing networks are left alone: this runs at",
        "# every boot, and recreating a network would disconnect every running service.",
        "set -euo pipefail",
        "",
    ]
    for network in _objects(systemd_policy.get("container_networks")):
        network_id = str(network["network_id"])
        subnet = str(network["subnet"])
        internal = " --internal" if network.get("internal") is True else ""
        body += [
            f"if ! docker network inspect {_quote(network_id)} >/dev/null 2>&1; then",
            f"  docker network create --driver bridge{internal} \\",
            f"    --subnet {_quote(subnet)} {_quote(network_id)} >/dev/null",
            f'  printf "created %s\\n" {_quote(network_id)}',
            "fi",
        ]
    body.append("")
    return "\n".join(body)


def _target_unit(services: list[dict[str, object]]) -> str:
    """Render one target so the whole POC can be started or stopped together."""
    wants = " ".join(sorted(str(service["unit_name"]) for service in services))
    return "\n".join(
        [
            _GENERATED,
            "[Unit]",
            "Description=AskLegal V1 POC",
            f"Wants={wants}",
            "After=asklegal-networks.service",
            "",
            "[Install]",
            "WantedBy=multi-user.target",
            "",
        ]
    )


def _credential_script(services: list[dict[str, object]]) -> str:
    """Render the root step that seals every credential to this host's TPM."""
    unique = sorted(
        {name for service in services for name in _strings(service.get("credential_names"))}
    )
    body = [
        "#!/usr/bin/env bash",
        _GENERATED,
        "#",
        "# Seal every V1 credential to this host, encrypted at rest.",
        "#",
        "# Reads one plaintext file per credential from a staging directory you supply,",
        "# and writes the sealed form under " + _SEALED_ROOT + ". The sealed files are",
        "# useless on any other machine. Delete the staging directory afterwards: this",
        "# script will not do it for you, because it does not own those files.",
        "#",
        "#   sudo ./70-credentials.sh /path/to/plaintext-staging",
        "set -euo pipefail",
        "",
        'staging="${1:-}"',
        'if [ -z "$staging" ] || [ ! -d "$staging" ]; then',
        '  printf "usage: %s <plaintext-staging-directory>\\n" "$0" >&2',
        "  exit 1",
        "fi",
        'if [ "$(id -u)" -ne 0 ]; then',
        '  printf "this step must run as root\\n" >&2',
        "  exit 1",
        "fi",
        "",
        f"install -d -o root -g root -m 0700 {_quote(_SEALED_ROOT)}",
        "",
        "# host+tpm2 binds the key to this machine's TPM. If the TPM is unavailable the",
        "# command fails rather than silently falling back to a host-only key.",
        "seal() {",
        '  local name="$1"',
        '  if [ ! -f "$staging/$name" ]; then',
        '    printf "missing plaintext credential: %s\\n" "$name" >&2',
        "    exit 1",
        "  fi",
        '  systemd-creds encrypt --with-key=host+tpm2 --name="$name" \\',
        f'    "$staging/$name" {_quote(_SEALED_ROOT)}/"$name".cred',
        f'  chmod 0400 {_quote(_SEALED_ROOT)}/"$name".cred',
        '  printf "sealed %s\\n" "$name"',
        "}",
        "",
    ]
    body.extend(f"seal {_quote(name)}" for name in unique)
    body += [
        "",
        f'printf "\\n%s credentials sealed under %s\\n" {len(unique)} {_quote(_SEALED_ROOT)}',
        'printf "Now delete your plaintext staging directory.\\n"',
        "",
    ]
    return "\n".join(body)


def _install_script(services: list[dict[str, object]]) -> str:
    """Render the root step that installs the units without enabling them."""
    unit_names = sorted(str(service["unit_name"]) for service in services)
    body = [
        "#!/usr/bin/env bash",
        _GENERATED,
        "#",
        "# Install the V1 POC units, launchers, and service configuration.",
        "#",
        "# This installs and does not enable. Nothing starts at boot until you run the",
        "# enable command this script prints at the end, so you can read every file",
        "# first. Run 70-credentials.sh before enabling, or every unit that needs a",
        "# credential will fail to start.",
        "set -euo pipefail",
        "",
        'if [ "$(id -u)" -ne 0 ]; then',
        '  printf "this step must run as root\\n" >&2',
        "  exit 1",
        "fi",
        'here="$(cd "$(dirname "$0")" && pwd)"',
        'repository="$(cd "$here/../../.." && pwd)"',
        "",
        f"install -d -o root -g root -m 0755 {_quote(_LAUNCH_ROOT)} {_quote(_CONFIG_ROOT)}",
        "install -d -o root -g root -m 0755 /etc/asklegal/trust",
        "",
        "# The internal authority has to be in the container trust store as well as on",
        "# its own, because the SQL driver validates against the system bundle.",
        "cat /etc/ssl/certs/ca-certificates.crt /etc/asklegal/tls/internal-ca.crt \\",
        "  > /etc/asklegal/trust/ca-certificates.crt",
        "chmod 0644 /etc/asklegal/trust/ca-certificates.crt",
        "for vault in vault-primary vault-recovery; do",
        '  cp /etc/asklegal/tls/internal-ca.crt "/etc/asklegal/trust/$vault-ca.pem"',
        '  chmod 0644 "/etc/asklegal/trust/$vault-ca.pem"',
        "done",
        "",
        "install -o root -g root -m 0644 \\",
        f'  "$repository"/infrastructure/poc/config/* {_quote(_CONFIG_ROOT)}/',
        f'install -o root -g root -m 0755 "$here"/launch/*.sh {_quote(_LAUNCH_ROOT)}/',
        'install -o root -g root -m 0644 "$here"/*.service "$here"/*.target /etc/systemd/system/',
        "",
        "systemctl daemon-reload",
        'printf "\\ninstalled %s units, not enabled\\n" ' + str(len(unit_names)),
        "",
        'printf "\\nWhen you are ready, and only after 70-credentials.sh:\\n"',
        'printf "  sudo systemctl enable --now asklegal.target\\n"',
        "",
    ]
    return "\n".join(body)


def render(root: Path) -> dict[str, str]:
    """Render every unit, launcher, and root step from the current contracts."""
    commands = _read(root, RUNTIME_COMMANDS_PATH)
    systemd_policy = _read(root, SYSTEMD_PATH)
    services = _objects(commands.get("services"))
    if not services:
        message = "no proven service runtime commands"
        raise UnitRenderError(message)
    ordering = _dependency_units(systemd_policy)
    rendered: dict[str, str] = {
        "asklegal-networks.service": _networks_unit(),
        "asklegal.target": _target_unit(services),
        "launch/networks.sh": _networks_launcher(systemd_policy),
        "70-credentials.sh": _credential_script(services),
        "80-install.sh": _install_script(services),
    }
    known = {str(service["unit_name"]) for service in services}
    for service in services:
        unit_name = str(service["unit_name"])
        service_id = str(service["service_id"])
        # A dependency on a unit this file does not render would never be satisfied.
        requires = [name for name in ordering.get(unit_name, []) if name in known]
        rendered[unit_name] = _unit_file(service, requires)
        rendered[f"launch/{service_id}.sh"] = _launcher(service)
    return rendered


def write(root: Path) -> tuple[str, ...]:
    """Write every rendered file with the mode its kind requires."""
    output = root / OUTPUT_ROOT
    (output / "launch").mkdir(parents=True, exist_ok=True)
    for name, content in sorted(render(root).items()):
        path = output / name
        path.write_text(content, encoding="utf-8")
        path.chmod(0o755 if name.endswith(".sh") else 0o644)
    return tuple(sorted(render(root)))


def check(root: Path) -> tuple[str, ...]:
    """Return the names of rendered files that differ from the current contracts."""
    output = root / OUTPUT_ROOT
    drifted: list[str] = []
    for name, content in sorted(render(root).items()):
        path = output / name
        if not path.is_file() or path.read_text(encoding="utf-8") != content:
            drifted.append(name)
    return tuple(drifted)


def main() -> None:
    """Render the units, or verify that they match the contracts."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify instead of writing")
    arguments = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    if arguments.check:
        drifted = check(root)
        if drifted:
            message = f"units differ from the contracts: {', '.join(drifted)}"
            raise UnitRenderError(message)
        print("PASS V1 POC units match the contracts")  # noqa: T201
        return
    names = write(root)
    print(f"rendered {len(names)} files under {OUTPUT_ROOT}")  # noqa: T201


if __name__ == "__main__":
    main()
