"""Render the V1 POC systemd units and their launchers from the contracts.

Like the provisioning scripts, these files are generated and never hand-written,
so they cannot drift from `service_runtime_commands.json`, `topology.json`,
`host_identity_inputs.json`, and `systemd_unit_inputs.json`. `--check` re-renders
and compares, so a hand edit or an unpropagated contract change fails the
ordinary test suite.

Two things shape every unit here.

Credentials never touch persistent plaintext. systemd decrypts each one into the
unit's own `$CREDENTIALS_DIRECTORY`, which is a tmpfs owned by root. The five
applications need a directory of files owned by their own runtime uid at mode
0400, so each launcher copies them into `/run/asklegal/credentials/<service>` with
that exact ownership before starting the container. SQL takes its bootstrap
secret from the host launcher environment. The two Versity launchers instead
mount their root credentials read-only and export them only inside the already-
created container. This keeps values out of both Docker create argv and Docker's
retained Config.Env while satisfying Versity's environment-only interface.

Nothing here is admitted. The units are rendered disabled, the five application
images are still local tags rather than digests, and installation, credential
sealing, and enablement are all separate root steps the user runs deliberately.
"""

from __future__ import annotations

import argparse
import json
import shutil
import tempfile
from pathlib import Path
from typing import cast

OUTPUT_ROOT = Path("infrastructure/poc/units")
RUNTIME_COMMANDS_PATH = Path("infrastructure/poc/service_runtime_commands.json")
SYSTEMD_PATH = Path("infrastructure/poc/systemd_unit_inputs.json")

_GENERATED = "# Generated by tools/v1_poc_render_units.py. Do not edit by hand."
_CREDENTIAL_ROOT = "/run/asklegal/credentials"
_LAUNCH_ROOT = "/etc/asklegal/launch"
_CONFIG_ROOT = "/etc/asklegal/config"
_SEALED_ROOT = "/etc/asklegal/credentials"
_STOP_SECONDS = 30
_TIMEOUT_STOP_SECONDS = 45


class UnitRenderError(RuntimeError):
    """One exact, secret-free unit rendering failure."""


def _read(root: Path, path: Path) -> dict[str, object]:
    value = json.loads((root / path).read_bytes())
    result = _string_object(value)
    if result is None:
        message = f"unit input root: {path}"
        raise UnitRenderError(message)
    return result


def _string_object(value: object) -> dict[str, object] | None:
    if not isinstance(value, dict):
        return None
    candidate = cast("dict[object, object]", value)
    if not all(type(key) is str for key in candidate):
        return None
    return cast("dict[str, object]", candidate)


def _objects(value: object) -> list[dict[str, object]]:
    if not isinstance(value, list):
        message = "unit object list"
        raise UnitRenderError(message)
    result: list[dict[str, object]] = []
    for item in cast("list[object]", value):
        candidate = _string_object(item)
        if candidate is None:
            message = "unit object list member"
            raise UnitRenderError(message)
        result.append(candidate)
    return result


def _strings(value: object) -> list[str]:
    if not isinstance(value, list):
        return []
    candidate = cast("list[object]", value)
    if not all(type(item) is str for item in candidate):
        message = "unit string list member"
        raise UnitRenderError(message)
    return cast("list[str]", candidate)


def _quote(value: str) -> str:
    """Quote one argument for a generated shell script."""
    return "'" + value.replace("'", "'\\''") + "'"


def _dependency_units(
    systemd_policy: dict[str, object],
) -> dict[str, tuple[list[str], list[str]]]:
    """Map each unit to its required and ordering-only dependencies."""
    ordering: dict[str, tuple[list[str], list[str]]] = {}
    for group in ("service_units", "bootstrap_units"):
        for unit in _objects(systemd_policy.get(group)):
            name = str(unit.get("unit_name", ""))
            if not name:
                continue
            ordering[name] = (
                _strings(unit.get("requires")),
                _strings(unit.get("after_targets")),
            )
    return ordering


def _unit_file(service: dict[str, object], requires: list[str], after_targets: list[str]) -> str:
    """Render one hardened service unit for an already-proven container."""
    service_id = str(service["service_id"])
    unit_name = str(service["unit_name"])
    required = ["docker.service", "asklegal-networks.service", *requires]
    ordering = list(dict.fromkeys((*required, *after_targets)))
    lines = [
        _GENERATED,
        "[Unit]",
        f"Description=AskLegal V1 POC {service_id}",
        f"Requires={' '.join(required)}",
        f"After={' '.join(ordering)}",
        "PartOf=asklegal.target",
        "",
        "[Service]",
        "Type=simple",
        "Restart=on-failure",
        "RestartSec=5",
        "NoNewPrivileges=true",
        "ProtectSystem=strict",
        "ProtectHome=true",
        "PrivateTmp=true",
        # The launcher installs credential files owned by the runtime uid at
        # 0400. An empty bounding set leaves root unable to chown, which fails
        # every unit before its container ever starts. These three are what the
        # preamble actually needs, and nothing else is granted.
        "CapabilityBoundingSet=CAP_CHOWN CAP_FOWNER CAP_DAC_OVERRIDE",
        # ProtectSystem=strict refuses to build the mount namespace if a
        # ReadWritePaths entry does not exist, so systemd has to create the
        # directory itself. Preserve it: several units share it, and the default
        # would delete it from under the others as soon as one stopped.
        "RuntimeDirectory=asklegal",
        "RuntimeDirectoryPreserve=yes",
        "ReadWritePaths=/run/asklegal",
    ]
    # Sealed to this host's TPM; systemd decrypts into $CREDENTIALS_DIRECTORY,
    # which is a tmpfs and disappears when the unit stops.
    lines.extend(
        f"LoadCredentialEncrypted={name}:{_SEALED_ROOT}/{name}.cred"
        for name in _strings(service.get("credential_names"))
    )
    lines += [
        f"ExecStart={_LAUNCH_ROOT}/{service_id}.sh",
        f"ExecStop=/usr/bin/docker stop --time={_STOP_SECONDS} asklegal-{service_id}",
        f"TimeoutStopSec={_TIMEOUT_STOP_SECONDS}",
        "",
        "[Install]",
        "WantedBy=multi-user.target",
        "",
    ]
    if not unit_name.endswith(".service"):
        message = f"unit name must be a service: {unit_name}"
        raise UnitRenderError(message)
    return "\n".join(lines)


def _credential_preamble(service: dict[str, object]) -> list[str]:
    """Render the lines that put this service's credentials where it expects them."""
    service_id = str(service["service_id"])
    delivery = str(service.get("credential_delivery", "NONE"))
    if delivery == "DIRECTORY_OWNED_BY_RUNTIME_UID":
        body = [
            "# The application reads its own credentials as files owned by its runtime",
            "# uid at mode 0400. $CREDENTIALS_DIRECTORY is root-owned, so copy rather",
            "# than mount it, onto /run, which is a tmpfs.",
            f"credential_dir={_quote(f'{_CREDENTIAL_ROOT}/{service_id}')}",
            'rm -rf "$credential_dir"',
            'mkdir -p "$credential_dir"',
        ]
        body.extend(
            f'install -o "$runtime_uid" -g "$runtime_uid" -m 0400 '
            f'"$CREDENTIALS_DIRECTORY"/{name} "$credential_dir"/{name}'
            for name in _strings(service.get("credential_names"))
        )
        return [
            *body,
            'chown "$runtime_uid":"$runtime_uid" "$credential_dir"',
            'chmod 0500 "$credential_dir"',
            "",
        ]
    if delivery == "ENVIRONMENT_FROM_LOADED_CREDENTIAL":
        body = [
            "# The secret reaches the container through the environment, never through",
            "# argv: `docker -e NAME` with no value passes the variable through.",
        ]
        for entry in _objects(service.get("credential_environment")):
            variable = str(entry["variable"])
            name = str(entry["credential"])
            body.append(f'{variable}="$(cat "$CREDENTIALS_DIRECTORY"/{name})"')
            body.append(f"export {variable}")
        return [*body, ""]
    if delivery == "READ_ONLY_FILES_TO_IN_CONTAINER_ENVIRONMENT":
        body = [
            "# Root credentials are mounted as read-only files. They are read only by",
            "# the in-container shell, so Docker Config.Env and create argv retain no value.",
            f"credential_dir={_quote(f'{_CREDENTIAL_ROOT}/{service_id}')}",
            'rm -rf "$credential_dir"',
            'mkdir -p "$credential_dir"',
        ]
        body.extend(
            f'install -o "$runtime_uid" -g "$runtime_uid" -m 0400 '
            f'"$CREDENTIALS_DIRECTORY"/{name} "$credential_dir"/{name}'
            for name in _strings(service.get("credential_names"))
        )
        return [
            *body,
            'chown "$runtime_uid":"$runtime_uid" "$credential_dir"',
            'chmod 0500 "$credential_dir"',
            "",
        ]
    return []


def _create_arguments(service: dict[str, object]) -> list[str]:
    """Render the exact `docker create` argument list for one proven service."""
    unit_name = str(service["unit_name"])
    first = _objects(service["networks"])[0]
    create = [
        "docker create",
        '  --name "$container"',
        f"  --network {_quote(str(first['network']))}",
        f"  --network-alias {_quote(str(first['alias']))}",
        '  --user "$runtime_uid":"$runtime_uid"',
        "  --cap-drop ALL",
        "  --security-opt no-new-privileges",
    ]
    if (ipv4_address := first.get("ipv4_address")) is not None:
        create.insert(4, f"  --ip {_quote(str(ipv4_address))}")
    if service.get("read_only_root") is True:
        create.append("  --read-only")
    create.extend(
        f"  --tmpfs {_quote(str(entry['target']))}"
        f":uid=$runtime_uid,gid=$runtime_uid,mode={entry.get('mode', '0700')}"
        for entry in _objects(service.get("tmpfs"))
    )
    create.extend(
        f"  -e {_quote(str(entry['name']) + '=' + str(entry['value']))}"
        for entry in _objects(service.get("environment"))
    )
    if str(service.get("credential_delivery")) == "ENVIRONMENT_FROM_LOADED_CREDENTIAL":
        create.extend(
            f"  -e {_quote(str(entry['variable']))}"
            for entry in _objects(service.get("credential_environment"))
        )
    create.extend(
        f"  --cap-add {_quote(capability)}"
        for capability in _strings(service.get("capabilities_add"))
    )
    if str(service.get("credential_delivery")) == "DIRECTORY_OWNED_BY_RUNTIME_UID":
        target = f"/run/credentials/{unit_name}"
        create.append(f"  -e {_quote(f'CREDENTIALS_DIRECTORY={target}')}")
        create.append(f'  -v "$credential_dir":{_quote(target)}:ro')
    if str(service.get("credential_delivery")) == "READ_ONLY_FILES_TO_IN_CONTAINER_ENVIRONMENT":
        for entry in _objects(service.get("credential_environment")):
            credential = str(entry["credential"])
            target = f"/run/asklegal/{credential}"
            create.append(
                f'  --mount "type=bind,src=${{credential_dir}}/{credential},dst={target},readonly"'
            )
        create.append(f"  --entrypoint {_quote('/bin/sh')}")
    create.extend(
        f"  -v {_quote(f'{entry["source"]}:{entry["target"]}:{entry.get("mode", "ro")}')}"
        for entry in _objects(service.get("mounts"))
    )
    image = str(service["image"])
    create.append('  "$image_id"' if image.startswith("asklegal/") else f"  {_quote(image)}")
    if str(service.get("credential_delivery")) == "READ_ONLY_FILES_TO_IN_CONTAINER_ENVIRONMENT":
        assignments: list[str] = []
        for entry in _objects(service.get("credential_environment")):
            variable = str(entry["variable"])
            credential = str(entry["credential"])
            assignments.append(f'{variable}="$(cat /run/asklegal/{credential})"; export {variable}')
        assignments.append('exec /usr/local/bin/docker-entrypoint.sh "$@"')
        create.extend(
            (
                f"  {_quote('-ceu')}",
                f"  {_quote('; '.join(assignments))}",
                f"  {_quote('asklegal-versity-file-entrypoint')}",
            )
        )
    create.extend(f"  {_quote(argument)}" for argument in _strings(service.get("command")))
    return create


def _launcher(service: dict[str, object]) -> str:
    """Render the launcher that turns one contract entry into a running container."""
    service_id = str(service["service_id"])
    uid = service["runtime_uid"]
    if type(uid) is not int:
        message = f"runtime uid for {service_id}"
        raise UnitRenderError(message)
    networks = _objects(service.get("networks"))
    if not networks:
        message = f"no network for {service_id}"
        raise UnitRenderError(message)

    body = [
        "#!/usr/bin/env bash",
        _GENERATED,
        "#",
        f"# Start {service_id} exactly as it was proved to run.",
        "set -euo pipefail",
        "",
        f"container={_quote(f'asklegal-{service_id}')}",
        f"runtime_uid={uid}",
        "",
    ]
    if str(service["image"]).startswith("asklegal/"):
        pattern = f"^{service_id} sha256:[0-9a-f]{{64}}$"
        body += [
            "# Phase two atomically installs this authority-bound exact image set.",
            "deployment_manifest=/etc/asklegal/deployment-images",
            '[ -f "$deployment_manifest" ] && [ ! -L "$deployment_manifest" ]',
            f'matches="$(grep -Ec \'{pattern}\' "$deployment_manifest")"',
            '[ "$matches" -eq 1 ]',
            f'image_line="$(grep -E \'{pattern}\' "$deployment_manifest")"',
            'image_id="${image_line#* }"',
            (
                "docker image inspect --format '{{.Id}}' \"$image_id\" | "
                'grep -Fx -- "$image_id" >/dev/null'
            ),
            "",
        ]
    body += [
        "# A stale container from a previous boot would keep the name and the old",
        "# configuration, so the unit always starts from a clean one.",
        'docker rm -f "$container" >/dev/null 2>&1 || true',
        "",
        *_credential_preamble(service),
        " \\\n".join(_create_arguments(service)) + " >/dev/null",
        "",
    ]
    if len(networks) > 1:
        body += [
            "# Every network is attached before the process starts. Attaching after start",
            "# is a race: the readiness gate can run before a dependency is reachable.",
        ]
        body.extend(
            "docker network connect "
            + (
                f"--ip {_quote(str(entry['ipv4_address']))} "
                if entry.get("ipv4_address") is not None
                else ""
            )
            + f"--alias {_quote(str(entry['alias']))} "
            + f'{_quote(str(entry["network"]))} "$container"'
            for entry in networks[1:]
        )
        body.append("")
    body += [
        "# `docker start --attach` keeps this script in the foreground so systemd can",
        "# supervise it; ExecStop stops the container itself.",
        'exec docker start --attach "$container"',
        "",
    ]
    return "\n".join(body)


def _networks_unit() -> str:
    """Render the bootstrap unit that guarantees the ten networks exist."""
    return "\n".join(
        [
            _GENERATED,
            "[Unit]",
            "Description=AskLegal V1 POC container networks",
            "Requires=docker.service",
            "After=docker.service",
            "",
            "[Service]",
            "Type=oneshot",
            "RemainAfterExit=true",
            "NoNewPrivileges=true",
            "ProtectSystem=strict",
            "ProtectHome=true",
            f"ExecStart={_LAUNCH_ROOT}/networks.sh",
            "",
            "[Install]",
            "WantedBy=multi-user.target",
            "",
        ]
    )


def _filesystems_target() -> str:
    """Require all persistent local stores before SQL or either vault can start."""
    return (
        f"{_GENERATED}\n[Unit]\nDescription=AskLegal V1 POC persistent filesystems\n"
        "RequiresMountsFor=/srv/asklegal/sql /srv/asklegal/vault-primary "
        "/srv/asklegal/vault-recovery\n"
    )


def _bootstrap_unit(unit: dict[str, object]) -> str:
    """Render a fail-visible privileged one-shot with fixed helper argv and readback."""
    name = str(unit["unit_name"])
    requires = _strings(unit.get("requires"))
    if name == "asklegal-register-migrate.service":
        helper = "/usr/local/libexec/asklegal-register-migrate"
        execute = (
            f"{helper} --migrations-root /opt/asklegal/management-register/migrations "
            "--credential-directory ${CREDENTIALS_DIRECTORY} "
            "--receipt /var/lib/asklegal/control/register-migration-readback.json"
        )
    elif name == "asklegal-vault-bootstrap.service":
        helper = "/usr/local/libexec/asklegal-vault-bootstrap"
        execute = (
            f"{helper} --credential-directory ${{CREDENTIALS_DIRECTORY}} "
            "--receipt /var/lib/asklegal/control/vault-bootstrap-readback.json"
        )
    else:
        message = f"unsupported bootstrap unit: {name}"
        raise UnitRenderError(message)
    lines = [
        _GENERATED,
        "[Unit]",
        f"Description=AskLegal V1 POC {name}",
        f"Requires={' '.join(requires)}",
        f"After={' '.join(requires)}",
        "Before=asklegal.target",
        "",
        "[Service]",
        "Type=oneshot",
        "RemainAfterExit=yes",
        "User=root",
        "Group=root",
        "UMask=0077",
        "NoNewPrivileges=true",
        "ProtectHome=true",
        "ProtectSystem=strict",
        "ReadWritePaths=/var/lib/asklegal/control",
    ]
    lines.extend(
        f"LoadCredentialEncrypted={credential}:{_SEALED_ROOT}/{credential}.cred"
        for credential in _strings(unit.get("credential_names"))
    )
    lines.extend(
        [
            f"ExecStart=/usr/bin/test -x {helper}",
            f"ExecStart={execute}",
            f"ExecStart={execute} --verify-only",
            "",
        ]
    )
    return "\n".join(lines)


def _networks_launcher(systemd_policy: dict[str, object]) -> str:
    """Render the idempotent network creation the bootstrap unit runs."""
    body = [
        "#!/usr/bin/env bash",
        _GENERATED,
        "#",
        "# Create any missing V1 network. Existing networks are left alone: this runs at",
        "# every boot, and recreating a network would disconnect every running service.",
        "set -euo pipefail",
        "",
    ]
    for network in _objects(systemd_policy.get("container_networks")):
        network_id = str(network["network_id"])
        subnet = str(network["subnet"])
        internal = " --internal" if network.get("internal") is True else ""
        body += [
            f"if ! docker network inspect {_quote(network_id)} >/dev/null 2>&1; then",
            f"  docker network create --driver bridge{internal} \\",
            f"    --subnet {_quote(subnet)} {_quote(network_id)} >/dev/null",
            f'  printf "created %s\\n" {_quote(network_id)}',
            "fi",
        ]
    body.append("")
    return "\n".join(body)


def _timer_unit(timer: dict[str, object]) -> str:
    """Render one persistent, non-jittered Asia/Hong_Kong timer."""
    timer_id = str(timer["timer_id"])
    unit_name = str(timer["unit_name"])
    trigger_unit_name = str(timer["trigger_unit_name"])
    if not unit_name.endswith(".timer") or not trigger_unit_name.endswith(".service"):
        message = f"timer unit names for {timer_id}"
        raise UnitRenderError(message)
    return "\n".join(
        [
            _GENERATED,
            "[Unit]",
            f"Description=AskLegal V1 POC {timer_id} schedule",
            "PartOf=asklegal.target",
            "Conflicts=shutdown.target",
            "Before=shutdown.target",
            "",
            "[Timer]",
            f"OnCalendar={timer['on_calendar']}",
            f"Unit={trigger_unit_name}",
            f"Persistent={str(timer['persistent']).lower()}",
            f"AccuracySec={timer['accuracy_sec']}",
            f"RandomizedDelaySec={timer['randomized_delay_sec']}",
            "",
            "[Install]",
            "WantedBy=asklegal.target",
            "",
        ]
    )


def _timer_trigger_unit(timer: dict[str, object]) -> str:
    """Render one bounded, shutdown-aware control-plane enqueue operation."""
    timer_id = str(timer["timer_id"])
    schedule_kind = str(timer["schedule_kind"])
    return "\n".join(
        [
            _GENERATED,
            "[Unit]",
            f"Description=AskLegal V1 POC {timer_id} enqueue",
            "Requires=asklegal-control-plane.service",
            "After=asklegal-control-plane.service",
            "PartOf=asklegal.target",
            "Conflicts=shutdown.target",
            "Before=shutdown.target",
            "",
            "[Service]",
            "Type=oneshot",
            "KillMode=control-group",
            "TimeoutStartSec=60",
            "TimeoutStopSec=30",
            (
                "# The invocation ID is delivery evidence only; Control derives the latest "
                "applicable Asia/Hong_Kong slot for catch-up."
            ),
            (
                "ExecStart=/usr/bin/docker exec asklegal-control-plane "
                f"asklegal-control-plane --enqueue-schedule {schedule_kind} "
                "--invocation-id ${INVOCATION_ID}"
            ),
            "",
        ]
    )


def _target_unit(services: list[dict[str, object]], timers: list[dict[str, object]]) -> str:
    """Render one target so the whole POC can be started or stopped together."""
    wants = " ".join(
        sorted(
            ["asklegal-filesystems.target"]
            + [str(service["unit_name"]) for service in services]
            + [str(timer["unit_name"]) for timer in timers]
        )
    )
    return "\n".join(
        [
            _GENERATED,
            "[Unit]",
            "Description=AskLegal V1 POC",
            f"Wants={wants}",
            "After=asklegal-networks.service",
            "",
            "[Install]",
            "WantedBy=multi-user.target",
            "",
        ]
    )


def _credential_script(services: list[dict[str, object]]) -> str:
    """Render the root step that seals every credential to this host's TPM."""
    unique = sorted(
        {name for service in services for name in _strings(service.get("credential_names"))}
    )
    body = [
        "#!/usr/bin/env bash",
        _GENERATED,
        "#",
        "# Seal every V1 credential to this host, encrypted at rest.",
        "#",
        "# Reads one plaintext file per credential from a staging directory you supply,",
        "# and writes the sealed form under " + _SEALED_ROOT + ". The sealed files are",
        "# useless on any other machine. Delete the staging directory afterwards: this",
        "# script will not do it for you, because it does not own those files.",
        "#",
        "#   sudo ./70-credentials.sh /path/to/plaintext-staging",
        "set -euo pipefail",
        "",
        'staging="${1:-}"',
        'if [ -z "$staging" ] || [ ! -d "$staging" ]; then',
        '  printf "usage: %s <plaintext-staging-directory>\\n" "$0" >&2',
        "  exit 1",
        "fi",
        'if [ "$(id -u)" -ne 0 ]; then',
        '  printf "this step must run as root\\n" >&2',
        "  exit 1",
        "fi",
        "",
        f"install -d -o root -g root -m 0700 {_quote(_SEALED_ROOT)}",
        "",
        "# host+tpm2 binds the key to this machine's TPM. If the TPM is unavailable the",
        "# command fails rather than silently falling back to a host-only key.",
        "seal() {",
        '  local name="$1"',
        '  if [ ! -f "$staging/$name" ]; then',
        '    printf "missing plaintext credential: %s\\n" "$name" >&2',
        "    exit 1",
        "  fi",
        '  systemd-creds encrypt --with-key=host+tpm2 --name="$name" \\',
        f'    "$staging/$name" {_quote(_SEALED_ROOT)}/"$name".cred',
        f'  chmod 0400 {_quote(_SEALED_ROOT)}/"$name".cred',
        '  printf "sealed %s\\n" "$name"',
        "}",
        "",
    ]
    body.extend(f"seal {_quote(name)}" for name in unique)
    body += [
        "",
        f'printf "\\n%s credentials sealed under %s\\n" {len(unique)} {_quote(_SEALED_ROOT)}',
        'printf "Now delete your plaintext staging directory.\\n"',
        "",
    ]
    return "\n".join(body)


def _install_script(
    services: list[dict[str, object]],
    timers: list[dict[str, object]],
    bootstrap: list[dict[str, object]],
) -> str:
    """Render the root step that installs the units without enabling them."""
    unit_names = sorted(
        [str(service["unit_name"]) for service in services]
        + [str(timer["unit_name"]) for timer in timers]
        + [str(timer["trigger_unit_name"]) for timer in timers]
        + [str(unit["unit_name"]) for unit in bootstrap]
    )
    body = [
        "#!/usr/bin/env bash",
        _GENERATED,
        "#",
        "# Install the V1 POC units, launchers, and service configuration.",
        "#",
        "# This installs and does not enable. Nothing starts at boot until you run the",
        "# enable command this script prints at the end, so you can read every file",
        "# first. Run 70-credentials.sh before enabling, or every unit that needs a",
        "# credential will fail to start.",
        "set -euo pipefail",
        "",
        'if [ "$(id -u)" -ne 0 ]; then',
        '  printf "this step must run as root\\n" >&2',
        "  exit 1",
        "fi",
        'here="$(cd "$(dirname "$0")" && pwd)"',
        'repository="$(cd "$here/../../.." && pwd)"',
        "",
        f"install -d -o root -g root -m 0755 {_quote(_LAUNCH_ROOT)} {_quote(_CONFIG_ROOT)}",
        "install -d -o root -g root -m 0755 /etc/asklegal/trust",
        "install -d -o root -g root -m 0755 /usr/local/libexec",
        "install -d -o root -g root -m 0755 /opt/asklegal/management-register",
        "",
        "# The internal authority has to be in the container trust store as well as on",
        "# its own, because the SQL driver validates against the system bundle.",
        "cat /etc/ssl/certs/ca-certificates.crt /etc/asklegal/tls/internal-ca.crt \\",
        "  > /etc/asklegal/trust/ca-certificates.crt",
        "chmod 0644 /etc/asklegal/trust/ca-certificates.crt",
        "for vault in vault-primary vault-recovery; do",
        '  cp /etc/asklegal/tls/internal-ca.crt "/etc/asklegal/trust/$vault-ca.pem"',
        '  chmod 0644 "/etc/asklegal/trust/$vault-ca.pem"',
        "done",
        "",
        "install -o root -g root -m 0644 \\",
        f'  "$repository"/infrastructure/poc/config/* {_quote(_CONFIG_ROOT)}/',
        f'install -o root -g root -m 0755 "$here"/launch/*.sh {_quote(_LAUNCH_ROOT)}/',
        (
            'install -o root -g root -m 0755 "$repository"/infrastructure/poc/libexec/'
            "asklegal-register-migrate /usr/local/libexec/asklegal-register-migrate"
        ),
        (
            'install -o root -g root -m 0755 "$repository"/infrastructure/poc/libexec/'
            "asklegal-vault-bootstrap /usr/local/libexec/asklegal-vault-bootstrap"
        ),
        (
            'install -o root -g root -m 0755 "$repository"/infrastructure/poc/libexec/'
            "asklegal-vault-application-rotation-network "
            "/usr/local/libexec/asklegal-vault-application-rotation-network"
        ),
        (
            'install -o root -g root -m 0755 "$repository"/infrastructure/poc/libexec/'
            "asklegal-vault-primary-root-rotation-network "
            "/usr/local/libexec/asklegal-vault-primary-root-rotation-network"
        ),
        'migration_stage="$(mktemp -d /opt/asklegal/management-register/.migrations.XXXXXXXX)"',
        "trap 'rm -rf -- \"$migration_stage\"' EXIT",
        (
            'cp -a "$repository"/packages/management-register-adapter/migrations/. '
            '"$migration_stage"/'
        ),
        'find "$migration_stage" -type d -exec chmod 0755 {} +',
        'find "$migration_stage" -type f -exec chmod 0644 {} +',
        'chown -R root:root "$migration_stage"',
        "rm -rf -- /opt/asklegal/management-register/migrations",
        'mv -- "$migration_stage" /opt/asklegal/management-register/migrations',
        "trap - EXIT",
        (
            'install -o root -g root -m 0644 "$here"/*.service "$here"/*.target '
            '"$here"/*.timer /etc/systemd/system/'
        ),
        "",
        "systemctl daemon-reload",
        'printf "\\ninstalled %s units, not enabled\\n" ' + str(len(unit_names)),
        "",
        'printf "\\nWhen you are ready, and only after 70-credentials.sh:\\n"',
        'printf "  sudo systemctl enable --now asklegal.target\\n"',
        "",
    ]
    return "\n".join(body)


def render(root: Path) -> dict[str, str]:
    """Render every unit, launcher, and root step from the current contracts."""
    commands = _read(root, RUNTIME_COMMANDS_PATH)
    systemd_policy = _read(root, SYSTEMD_PATH)
    services = _objects(commands.get("services"))
    timers = _objects(systemd_policy.get("timer_units"))
    bootstrap = _objects(systemd_policy.get("bootstrap_units"))
    if not services:
        message = "no proven service runtime commands"
        raise UnitRenderError(message)
    ordering = _dependency_units(systemd_policy)
    rendered: dict[str, str] = {
        "asklegal-networks.service": _networks_unit(),
        "asklegal-filesystems.target": _filesystems_target(),
        "asklegal.target": _target_unit(services, timers),
        "launch/networks.sh": _networks_launcher(systemd_policy),
        "70-credentials.sh": _credential_script(services),
        "80-install.sh": _install_script(services, timers, bootstrap),
    }
    for unit in bootstrap:
        name = str(unit["unit_name"])
        if name in {"asklegal-networks.service", "asklegal-filesystems.target"}:
            continue
        rendered[name] = _bootstrap_unit(unit)
    known = set(rendered) | {str(service["unit_name"]) for service in services}
    for service in services:
        unit_name = str(service["unit_name"])
        service_id = str(service["service_id"])
        requires, after_targets = ordering.get(unit_name, ([], []))
        missing = [name for name in (*requires, *after_targets) if name not in known]
        if missing:
            message = f"unrendered dependency for {unit_name}: {missing[0]}"
            raise UnitRenderError(message)
        rendered[unit_name] = _unit_file(service, requires, after_targets)
        rendered[f"launch/{service_id}.sh"] = _launcher(service)
    for timer in timers:
        rendered[str(timer["unit_name"])] = _timer_unit(timer)
        rendered[str(timer["trigger_unit_name"])] = _timer_trigger_unit(timer)
    return rendered


def _write_tree(root: Path, output: Path) -> tuple[str, ...]:
    """Write one complete rendered tree at an already selected local path."""
    (output / "launch").mkdir(parents=True, exist_ok=True)
    rendered = render(root)
    for name, content in sorted(rendered.items()):
        path = output / name
        path.write_text(content, encoding="utf-8")
        path.chmod(0o755 if name.endswith(".sh") else 0o644)
    return tuple(sorted(rendered))


def write(root: Path) -> tuple[str, ...]:
    """Write every rendered file with the mode its kind requires."""
    return _write_tree(root, root / OUTPUT_ROOT)


def write_preview(root: Path, output: Path) -> tuple[str, ...]:
    """Atomically create one explicit review tree without touching checked-in units."""
    destination = output if output.is_absolute() else root / output
    if destination.exists() or destination.is_symlink():
        message = "preview output already exists"
        raise ValueError(message)
    destination.parent.mkdir(parents=True, exist_ok=True)
    if destination.parent.resolve(strict=True) != destination.parent.absolute():
        message = "preview output parent contains a symlink"
        raise ValueError(message)
    temporary = Path(tempfile.mkdtemp(prefix=f".{destination.name}.", dir=destination.parent))
    try:
        names = _write_tree(root, temporary)
        temporary.replace(destination)
    finally:
        if temporary.exists():
            shutil.rmtree(temporary)
    return names


def check(root: Path) -> tuple[str, ...]:
    """Return the names of rendered files that differ from the current contracts."""
    output = root / OUTPUT_ROOT
    drifted: list[str] = []
    for name, content in sorted(render(root).items()):
        path = output / name
        if not path.is_file() or path.read_text(encoding="utf-8") != content:
            drifted.append(name)
    return tuple(drifted)


def main() -> None:
    """Render the units, or verify that they match the contracts."""
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="verify instead of writing")
    mode.add_argument("--output", type=Path, help="create a separate deterministic preview tree")
    arguments = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    if arguments.check:
        drifted = check(root)
        if drifted:
            message = f"units differ from the contracts: {', '.join(drifted)}"
            raise UnitRenderError(message)
        print("PASS V1 POC units match the contracts")  # noqa: T201
        return
    if arguments.output is not None:
        names = write_preview(root, arguments.output)
        print(f"rendered {len(names)} preview files under {arguments.output}")  # noqa: T201
        return
    names = write(root)
    print(f"rendered {len(names)} files under {OUTPUT_ROOT}")  # noqa: T201


if __name__ == "__main__":
    main()
