#!/usr/bin/env bash
# Generated by tools/v1_poc_render_provisioning.py. Do not edit by hand.
#
# Step 10 — read-only preflight
#
set -euo pipefail

DRY_RUN="${DRY_RUN:-0}"

run() {
  if [ "$DRY_RUN" = "1" ]; then
    printf '  would run: %s\n' "$*"
  else
    "$@"
  fi
}

note() { printf '%s\n' "$*"; }

require_root() {
  if [ "$(id -u)" -ne 0 ] && [ "$DRY_RUN" != "1" ]; then
    note "this step must run as root; re-run with sudo, or set DRY_RUN=1 to preview"
    exit 1
  fi
}

# Reads only. Changes nothing. Run this first and read the output.

failures=0

fail() { note "  FAIL  $*"; failures=$((failures + 1)); }
pass() { note "  ok    $*"; }

check_package() {
  local name="$1" expected="$2" actual
  actual="$(dpkg-query --showformat='${Version}' --show "$name" 2>/dev/null || true)"
  if [ "$actual" = "$expected" ]; then pass "$name $expected"; else
    fail "$name expected $expected, found ${actual:-NOT_INSTALLED}"
  fi
}

note "operating system"
if [ "$(. /etc/os-release && printf '%s %s' "$ID" "$VERSION_ID")" = "ubuntu 24.04" ]; then
  pass "ubuntu 24.04"
else
  fail "expected ubuntu 24.04"
fi
if [ "$(uname -m)" = "x86_64" ]; then pass "x86_64"; else fail "expected x86_64"; fi

note "locked host packages"
check_package ca-certificates "20260601~24.04.1"
check_package containerd.io "2.3.3-1~ubuntu.24.04~noble"
check_package docker-ce "5:29.7.2-1~ubuntu.24.04~noble"
check_package docker-ce-cli "5:29.7.2-1~ubuntu.24.04~noble"
check_package e2fsprogs "1.47.0-2.4~exp1ubuntu4.1"
check_package nftables "1.0.9-1ubuntu0.1"
check_package systemd "255.4-1ubuntu8.17"
check_package systemd-timesyncd "255.4-1ubuntu8.17"
check_package util-linux "2.39.3-9ubuntu6.5"

note "data disk"
if blkid -U "3667a2bf-a59b-485c-b07a-2150c1a18d63" >/dev/null 2>&1; then
  pass "disk 3667a2bf-a59b-485c-b07a-2150c1a18d63 present"
else
  fail "disk 3667a2bf-a59b-485c-b07a-2150c1a18d63 not found"
fi

note "credential protection"
if systemd-creds has-tpm2 >/dev/null 2>&1; then
  pass "TPM2 available for systemd-creds"
else
  note "  note  no TPM2; HOST_KEY_ONLY protection would apply"
fi

note "numeric identities are free"
allocated="3000 3001 3002 3003 3004 3005 3006 3007 3008 3009"
reserved="3010 3011 3012 3013 3014 10001"
for id in $allocated $reserved; do
  if getent passwd "$id" >/dev/null || getent group "$id" >/dev/null; then
    existing="$(getent passwd "$id" | cut -d: -f1)"
    case "$existing" in
      asklegal-*) pass "$id already held by $existing" ;;
      *) fail "$id is taken by ${existing:-a group}" ;;
    esac
  else
    pass "$id free"
  fi
done

note ""
if [ "$failures" -eq 0 ]; then
  note "preflight passed; nothing was changed"
else
  note "preflight found $failures problem(s); do not continue until they are resolved"
  exit 1
fi
