#!/usr/bin/env bash
# Generated by tools/v1_poc_render_provisioning.py. Do not edit by hand.
#
# Step 20 — mount the data disk at /srv/asklegal
#
set -euo pipefail

DRY_RUN="${DRY_RUN:-0}"

run() {
  if [ "$DRY_RUN" = "1" ]; then
    printf '  would run: %s\n' "$*"
  else
    "$@"
  fi
}

note() { printf '%s\n' "$*"; }

require_root() {
  if [ "$(id -u)" -ne 0 ] && [ "$DRY_RUN" != "1" ]; then
    note "this step must run as root; re-run with sudo, or set DRY_RUN=1 to preview"
    exit 1
  fi
}

# The three evidence and database paths must sit on one ext4 disk at a stable
# system path. The 4.0 TB disk is currently auto-mounted by the desktop session
# under /media, which is not a stable location for a service. This moves it to
# /srv/asklegal through /etc/fstab, by UUID.
#
# Recovery stays LOGICALLY_SEPARATE_POC_RECOVERY: both vaults share this disk,
# so losing it loses both. That limitation is accepted and unchanged here.

require_root

UUID="3667a2bf-a59b-485c-b07a-2150c1a18d63"
MOUNTPOINT="/srv/asklegal"
FSTAB_LINE="UUID=$UUID $MOUNTPOINT ext4 defaults,noatime,nofail 0 2"

if ! blkid -U "$UUID" >/dev/null 2>&1; then
  note "disk $UUID not found; refusing to continue"
  exit 1
fi

current="$(findmnt --noheadings --output TARGET --source "/dev/disk/by-uuid/$UUID" || true)"
if [ -n "$current" ] && [ "$current" != "$MOUNTPOINT" ]; then
  note "unmounting the desktop automount at $current"
  run umount "$current"
fi

run mkdir -p "$MOUNTPOINT"

if grep -q "UUID=$UUID" /etc/fstab; then
  note "fstab already references $UUID"
else
  note "adding the fstab entry"
  if [ "$DRY_RUN" = "1" ]; then
    printf '  would append: %s\n' "$FSTAB_LINE"
  else
    cp /etc/fstab "/etc/fstab.asklegal-backup.$(date +%s)"
    printf '%s\n' "$FSTAB_LINE" >> /etc/fstab
  fi
fi

run systemctl daemon-reload
if ! findmnt --mountpoint "$MOUNTPOINT" >/dev/null 2>&1; then
  run mount "$MOUNTPOINT"
fi

if [ "$DRY_RUN" != "1" ]; then
  findmnt --mountpoint "$MOUNTPOINT" --output SOURCE,FSTYPE,SIZE,TARGET
fi
run chown root:root "$MOUNTPOINT"
run chmod 0755 "$MOUNTPOINT"
note "storage ready"
