#!/usr/bin/env bash
# Generated by tools/v1_poc_render_provisioning.py. Do not edit by hand.
#
# Step 40 — private container networks
#
set -euo pipefail

DRY_RUN="${DRY_RUN:-0}"

run() {
  if [ "$DRY_RUN" = "1" ]; then
    printf '  would run: %s\n' "$*"
  else
    "$@"
  fi
}

note() { printf '%s\n' "$*"; }

require_root() {
  if [ "$(id -u)" -ne 0 ] && [ "$DRY_RUN" != "1" ]; then
    note "this step must run as root; re-run with sudo, or set DRY_RUN=1 to preview"
    exit 1
  fi
}

# Ten networks on collision-free /24 subnets from 10.90.0.0/16, chosen to avoid
# this host's LAN, VPN, and Docker's own bridge and default pool.
#
# Seven are internal: Docker gives them no route off the host at all. The three
# egress networks are routable because the proxy on each one has to reach its
# allowlisted destinations. That means a worker attached to an egress network
# also has a route out, which Docker alone does not restrict — see the note at
# the end of this file.

require_root

create_network() {
  local name="$1" subnet="$2" isolation="$3"
  if docker network inspect "$name" >/dev/null 2>&1; then
    local existing
    local format='{{range .IPAM.Config}}{{.Subnet}}{{end}}'
    existing="$(docker network inspect --format "$format" "$name")"
    if [ "$existing" != "$subnet" ]; then
      note "network $name exists on $existing, expected $subnet; refusing"
      exit 1
    fi
    note "  network $name already correct"
    return
  fi
  if [ "$isolation" = "internal" ]; then
    run docker network create --driver bridge --internal --subnet "$subnet" "$name"
  else
    run docker network create --driver bridge --subnet "$subnet" "$name"
  fi
}

create_network "asklegal-egress-model" "10.90.8.0/24" routable
create_network "asklegal-egress-promotion" "10.90.9.0/24" routable
create_network "asklegal-egress-source" "10.90.7.0/24" routable
create_network "asklegal-register" "10.90.0.0/24" internal
create_network "asklegal-review" "10.90.5.0/24" internal
create_network "asklegal-scheduler-general" "10.90.1.0/24" internal
create_network "asklegal-scheduler-promotion" "10.90.2.0/24" internal
create_network "asklegal-telemetry" "10.90.6.0/24" internal
create_network "asklegal-vault-primary" "10.90.3.0/24" internal
create_network "asklegal-vault-recovery" "10.90.4.0/24" internal

note "container networks ready"
note ""
note "OPEN ITEM — per-container egress is not yet enforced."
note "The accepted topology gives acquisition, legal-processing, and promotion an"
note "outbound profile of OFFICIAL_SOURCE_ONLY, MODEL_PROVIDER_ONLY, and"
note "PINECONE_AND_EMBEDDING_ONLY. Docker cannot express that on its own: on a"
note "routable network every member can reach outside, not just the proxy."
note "Closing it needs a decision: either give each proxy a fixed address and"
note "restrict the subnet in Docker's DOCKER-USER chain, or dual-home each proxy"
note "so the worker sits only on an internal network. Neither is applied here."
