#!/usr/bin/env bash
# Generated by tools/v1_poc_render_provisioning.py. Do not edit by hand.
#
# Step 50 — persistent sealed journal and time
#
set -euo pipefail

DRY_RUN="${DRY_RUN:-0}"

run() {
  if [ "$DRY_RUN" = "1" ]; then
    printf '  would run: %s\n' "$*"
  else
    "$@"
  fi
}

note() { printf '%s\n' "$*"; }

require_root() {
  if [ "$(id -u)" -ne 0 ] && [ "$DRY_RUN" != "1" ]; then
    note "this step must run as root; re-run with sudo, or set DRY_RUN=1 to preview"
    exit 1
  fi
}

# Host admission requires a persistent, forward-secure-sealed journal and working
# time synchronization. Sealing needs a key pair; this generates one if absent.

require_root

CONF=/etc/systemd/journald.conf.d/asklegal.conf

run install -d -o root -g root -m 0755 /etc/systemd/journald.conf.d
if [ "$DRY_RUN" = "1" ]; then
  printf '  would write: %s\n' "$CONF"
else
  cat > "$CONF" <<'CONFEOF'
# Generated by tools/v1_poc_render_provisioning.py. Do not edit by hand.
[Journal]
Storage=persistent
Seal=yes
CONFEOF
fi

run systemctl restart systemd-journald

sealing_key_present() {
  compgen -G "/var/log/journal/*/fss" > /dev/null 2>&1
}

if [ "$DRY_RUN" = "1" ]; then
  note "  would generate the forward-secure sealing key if absent"
elif sealing_key_present; then
  note "forward-secure sealing key already present"
else
  note "generating the forward-secure sealing key"
  note "this prints a verification key once; write it down, it is not stored here"
  journalctl --setup-keys --interval=1day || note "sealing key setup reported a problem"
fi

if timedatectl show --property=NTP --value | grep -q '^yes$'; then
  note "time synchronization already enabled"
else
  run timedatectl set-ntp true
fi

note "journal and time ready"
