#!/usr/bin/env bash
# Generated by tools/v1_poc_render_provisioning.py. Do not edit by hand.
#
# Step 60 — host input firewall (RUN SEPARATELY)
#
set -euo pipefail

DRY_RUN="${DRY_RUN:-0}"

run() {
  if [ "$DRY_RUN" = "1" ]; then
    printf '  would run: %s\n' "$*"
  else
    "$@"
  fi
}

note() { printf '%s\n' "$*"; }

require_root() {
  if [ "$(id -u)" -ne 0 ] && [ "$DRY_RUN" != "1" ]; then
    note "this step must run as root; re-run with sudo, or set DRY_RUN=1 to preview"
    exit 1
  fi
}

# ============================ READ THIS FIRST ============================
#
# This is the one step that can lock you out of this machine. It sets a
# default-deny policy on inbound host traffic. If you administer this host over
# SSH, applying it will drop your session and you will need physical access.
#
# provision.sh does NOT run this. Run it deliberately, at the console.
#
# It adds one separate nftables table, `inet asklegal`. Its forward hook keeps
# unrelated host forwarding intact, permits AskLegal internal traffic and
# established replies, and permits only the three fixed proxy addresses to
# originate traffic outside 10.90.0.0/16. Other AskLegal containers therefore
# cannot bypass their proxy on a routable egress bridge.
#
# To undo everything this does:   nft delete table inet asklegal
#
# A dead-man timer is armed by default: unless you confirm within the timeout,
# the rules are removed automatically.
# =========================================================================

require_root

CONFIRM_SECONDS="${CONFIRM_SECONDS:-120}"
SKIP_DEADMAN="${SKIP_DEADMAN:-0}"

if [ "${I_HAVE_CONSOLE_ACCESS:-0}" != "1" ] && [ "$DRY_RUN" != "1" ]; then
  note "refusing to apply an input default-deny policy without confirmation."
  note "re-run as: I_HAVE_CONSOLE_ACCESS=1 $0"
  exit 1
fi

apply_rules() {
  nft -f - <<'NFTEOF'
table inet asklegal {
  chain input {
    type filter hook input priority filter; policy drop;
    ct state established,related accept
    ct state invalid drop
    iif lo accept
    ip protocol icmp accept
    ip6 nexthdr ipv6-icmp accept
  }
  chain asklegal-container-egress {
    type filter hook forward priority -10; policy drop;
    ct state established,related accept
    ct state invalid drop
    ip saddr != 10.90.0.0/16 accept
    ip daddr 10.90.0.0/16 accept
    ip saddr { 10.90.7.2, 10.90.8.2, 10.90.9.2 } accept
  }
}
NFTEOF
}

if [ "$DRY_RUN" = "1" ]; then
  note "would add nftables table inet asklegal with input and AskLegal-egress default deny"
  note "would arm a ${CONFIRM_SECONDS}s dead-man revert"
  exit 0
fi

if [ "$SKIP_DEADMAN" != "1" ]; then
  rm -f /run/asklegal-firewall-confirmed
  note "arming a ${CONFIRM_SECONDS}s dead-man revert"
  setsid bash -c "sleep $CONFIRM_SECONDS; \
    if [ ! -f /run/asklegal-firewall-confirmed ]; then \
      nft delete table inet asklegal 2>/dev/null || true; \
    fi" >/dev/null 2>&1 &
fi

apply_rules
note "input and direct-container-egress default-deny applied."
note ""
note "Confirm within ${CONFIRM_SECONDS}s to keep it:"
note "  touch /run/asklegal-firewall-confirmed"
note "Otherwise it reverts by itself. To remove it now:"
note "  nft delete table inet asklegal"
