#!/usr/bin/env bash
# Generated by tools/v1_poc_render_provisioning.py. Do not edit by hand.
#
# V1 POC host provisioning
#
set -euo pipefail

DRY_RUN="${DRY_RUN:-0}"

run() {
  if [ "$DRY_RUN" = "1" ]; then
    printf '  would run: %s\n' "$*"
  else
    "$@"
  fi
}

note() { printf '%s\n' "$*"; }

require_root() {
  if [ "$(id -u)" -ne 0 ] && [ "$DRY_RUN" != "1" ]; then
    note "this step must run as root; re-run with sudo, or set DRY_RUN=1 to preview"
    exit 1
  fi
}

# Runs steps 10 through 50 in order. Step 60, the firewall, is deliberately not
# run here: it can lock you out and must be run on its own, at the console.
#
# Preview everything without changing anything:   DRY_RUN=1 ./provision.sh
#
# This installs no systemd unit, enables no service, pulls no image, and creates
# no credential. Those remain behind their own gates.

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

for step in 10-preflight 20-storage 30-identities 40-networks 50-journal-time; do
  note ""
  note "=== $step ==="
  DRY_RUN="$DRY_RUN" bash "$HERE/$step.sh"
done

note ""
note "=== done ==="
note "host storage, identities, directories, networks, journal, and time are ready."
note "Not done here, on purpose:"
note "  - step 60 firewall (run it yourself, at the console)"
note "  - internal TLS certificates for SQL, both vaults, and Review"
note "  - systemd units, image pulls, credentials, and service enablement"
